'use client';

import { useState, useMemo, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { 
  Save, Truck, 
  Calculator, ShieldCheck, 
  LayoutGrid,
  Zap, HardHat, 
  Wrench, Info, Loader2,
  RefreshCw, Clock
} from "lucide-react";
import { 
  Select, 
  SelectContent, 
  SelectItem, 
  SelectTrigger, 
  SelectValue 
} from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Equipment, EquipmentCategory, ToolCondition } from '@/types/equipment';
import { cn } from '@/lib/utils';
import { useFirestore, useCollection } from '@/firebase';
import { collection, query, orderBy } from 'firebase/firestore';
import { paths } from '@/firebase/multi-tenant';
import { useAuthContext } from '@/context/auth-context';
import { SmartDateInput } from '@/components/ui/smart-date-input';
import { toast } from '@/hooks/use-toast';

interface Props {
  initialData?: Partial<Equipment>;
  onSubmit: (data: any) => void;
  loading: boolean;
  isRtl: boolean;
}

export function EquipmentForm({ initialData, onSubmit, loading, isRtl }: Props) {
  const { globalUser } = useAuthContext();
  const db = useFirestore();
  const companyId = globalUser?.companyId;

  const categoryPrefixes: Record<string, string> = {
    heavy_machinery: 'HM',
    vehicle: 'VH',
    stationary: 'ST',
    hand_tool: 'HT',
    other: 'EQ'
  };

  const [form, setForm] = useState<any>({
    code: '', 
    name: '', 
    category: 'heavy_machinery', 
    ownershipType: 'owned', 
    manufacturingYear: '', // Will store 4 digits e.g. "2024"
    isLicensed: false,
    isStreetLicensed: false,
    chassisNumber: '',
    plateNumber: '',
    registrationNumber: '',
    registrationExpiry: '',
    insuranceType: 'none',
    insuranceCompany: '',
    insuranceExpiry: '',
    thirdPartyInspectionExpiry: '',
    siteInsuranceExpiry: '',
    serialNumber: '',
    capacity: '',
    nextServiceDate: '',
    safetyCertExpiry: '',
    brandModel: '',
    toolCondition: 'new',
    purchaseCost: '', 
    salvageValue: '', 
    depreciationMethod: 'hours', 
    isFinanced: false,
    financierName: '',
    monthlyInstallment: '',
    installmentDay: '',
    supplierId: '',
    supplierName: '',
    costMethod: 'hourly',
    costValue: '',
    hourlyDepreciationRate: '',
    hourlyRentalRate: '',
    status: 'available',
    isActive: true,
    ...initialData
  });

  useEffect(() => {
    if (!initialData?.id && form.category) {
      const prefix = categoryPrefixes[form.category] || 'EQ';
      const currentCode = form.code || '';
      const isAutoGenerated = !currentCode || Object.values(categoryPrefixes).some(p => currentCode.startsWith(p + '-'));
      
      if (isAutoGenerated) {
        const randomSuffix = Math.floor(1000 + Math.random() * 8999);
        setForm((prev: any) => ({ ...prev, code: `${prefix}-${randomSuffix}` }));
      }
    }
  }, [form.category, initialData?.id]);

  const suppliersQuery = useMemo(() => 
    companyId && db ? query(collection(db, paths.suppliers(companyId)), orderBy('name')) : null, 
  [db, companyId]);
  const { data: suppliers } = useCollection<any>(suppliersQuery);

  const isOwned = form.ownershipType === 'owned';
  const cat = form.category;

  const handlePreSubmit = () => {
    if (isOwned) {
      if (cat === 'vehicle' || (cat === 'heavy_machinery' && form.isStreetLicensed)) {
        if (!form.registrationExpiry || !form.insuranceExpiry) {
          toast({ 
            variant: "destructive", 
            title: isRtl ? "بيانات ناقصة" : "Missing Data", 
            description: isRtl ? "يجب إدخال تواريخ انتهاء الترخيص والتأمين للمركبات." : "Reg and Insurance expiry dates are required."
          });
          return;
        }
      }
    }

    // Final Year Validation
    if (form.manufacturingYear) {
      const year = parseInt(form.manufacturingYear);
      if (year < 1980) {
        toast({ 
          variant: "destructive", 
          title: isRtl ? "سنة غير صالحة" : "Invalid Year", 
          description: isRtl ? "سنة الصنع لا يمكن أن تكون قبل 1980." : "Manufacturing year cannot be before 1980."
        });
        return;
      }
    }

    onSubmit(form);
  };

  const AdminSectionHeader = ({ title, sub, icon: Icon, colorClass = "text-primary" }: any) => (
    <div className="flex items-center gap-4 text-start">
      <div className={cn("h-12 w-12 bg-white rounded-2xl flex items-center justify-center shadow-sm border", colorClass === "text-primary" ? "border-primary/10" : "border-secondary/10")}>
        <Icon className={cn("h-6 w-6", colorClass)} />
      </div>
      <div>
        <CardTitle className="text-xl font-black">{title}</CardTitle>
        <p className="text-[10px] font-bold text-slate-400 uppercase mt-1 tracking-widest">{sub}</p>
      </div>
    </div>
  );

  return (
    <div className="space-y-8 text-start pb-20 animate-in fade-in duration-700 bg-transparent">
      
      {/* 1. قسم الهوية والتصنيف */}
      <Card className="border-0 shadow-xl rounded-[2.5rem] bg-white overflow-hidden ring-1 ring-black/5">
        <CardHeader className="bg-primary/5 p-8 border-b">
           <div className="flex items-center gap-4">
              <div className="h-12 w-12 bg-white rounded-2xl flex items-center justify-center text-primary shadow-sm border border-primary/10">
                 <LayoutGrid className="h-6 w-6" />
              </div>
              <div>
                 <CardTitle className="text-xl font-black">{isRtl ? 'هوية الأصل والفئة' : 'Identity & Category'}</CardTitle>
                 <p className="text-[10px] font-bold text-slate-400 uppercase mt-1 tracking-widest">{isRtl ? 'توليد تلقائي للكود بناءً على الفئة المختارة' : 'Abbreviation-based Auto Coding'}</p>
              </div>
           </div>
        </CardHeader>
        <CardContent className="p-8">
           <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
              <div className="space-y-2">
                 <Label className="text-[10px] font-black uppercase text-slate-400 tracking-widest">{isRtl ? 'كود المعدة (تلقائي)' : 'Equipment Code'}</Label>
                 <div className="relative">
                    <Input 
                      value={form.code ?? ''} 
                      onChange={e => setForm({...form, code: e.target.value.toUpperCase()})} 
                      className="h-12 rounded-xl border-2 font-mono font-black text-primary bg-slate-50/50" 
                    />
                    <RefreshCw className="absolute end-4 top-1/2 -translate-y-1/2 h-4 w-4 text-primary/20 animate-pulse" />
                 </div>
              </div>
              <div className="md:col-span-2 space-y-2">
                 <Label className="text-[10px] font-black uppercase text-slate-400 tracking-widest">{isRtl ? 'اسم المعدة / الوصف' : 'Equipment Name'}</Label>
                 <Input 
                   value={form.name ?? ''} 
                   onChange={e => setForm({...form, name: e.target.value})} 
                   className="h-12 rounded-xl border-2 font-bold bg-white" 
                   placeholder={isRtl ? "مثلاً: حفار كوماتسو 200" : "e.g. Komatsu Excavator 200"}
                 />
              </div>
              <div className="space-y-2">
                 <Label className="text-[10px] font-black uppercase text-slate-400 tracking-widest">{isRtl ? 'تصنيف المعدة' : 'Category'}</Label>
                 <Select value={form.category ?? 'heavy_machinery'} onValueChange={(v: EquipmentCategory) => setForm({...form, category: v})}>
                    <SelectTrigger className="h-12 rounded-xl border-2 font-black bg-white"><SelectValue /></SelectTrigger>
                    <SelectContent className="rounded-xl">
                       <SelectItem value="heavy_machinery" className="font-bold">{isRtl ? 'آليات ثقيلة (HM)' : 'Heavy Machinery'}</SelectItem>
                       <SelectItem value="vehicle" className="font-bold">{isRtl ? 'مركبات (VH)' : 'Vehicles'}</SelectItem>
                       <SelectItem value="stationary" className="font-bold">{isRtl ? 'معدات ثابتة (ST)' : 'Stationary'}</SelectItem>
                       <SelectItem value="hand_tool" className="font-bold">{isRtl ? 'أدوات يدوية (HT)' : 'Hand Tools'}</SelectItem>
                       <SelectItem value="other" className="font-bold">{isRtl ? 'أخرى (EQ)' : 'Other'}</SelectItem>
                    </SelectContent>
                 </Select>
              </div>
           </div>
        </CardContent>
      </Card>

      {/* 2. البيانات الإدارية والتراخيص (تتغير ديناميكياً) */}
      <Card className="border-0 shadow-xl rounded-[3rem] bg-white overflow-hidden ring-1 ring-black/5">
         <CardHeader className="bg-slate-50/50 p-8 border-b">
            {cat === 'heavy_machinery' && (
              <div className="flex flex-col md:flex-row justify-between items-center gap-6">
                 <AdminSectionHeader title={isRtl ? 'بيانات الآلية الثقيلة' : 'Heavy Machinery'} sub={isRtl ? 'الامتثال الميداني والمروري' : 'Field vs Street Compliance'} icon={HardHat} colorClass="text-secondary" />
                 <div className="flex items-center gap-4 bg-white px-6 py-2.5 rounded-2xl border-2 shadow-sm">
                    <Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'مرخصة للسير في الشارع؟' : 'Street Licensed?'}</Label>
                    <Switch checked={form.isStreetLicensed} onCheckedChange={v => setForm({...form, isStreetLicensed: v})} />
                 </div>
              </div>
            )}
            {cat === 'vehicle' && <AdminSectionHeader title={isRtl ? 'بيانات ترخيص المركبة' : 'Vehicle Licensing'} sub={isRtl ? 'المرور والتأمين' : 'Traffic & Insurance'} icon={Truck} colorClass="text-secondary" />}
            {cat === 'stationary' && <AdminSectionHeader title={isRtl ? 'الصيانة والسلامة' : 'Maintenance & Safety'} sub={isRtl ? 'الفحص الدوري والشهادات' : 'Service & Certification'} icon={Zap} colorClass="text-secondary" />}
            {cat === 'hand_tool' && <AdminSectionHeader title={isRtl ? 'الماركة والحالة الفنية' : 'Brand & Condition'} sub={isRtl ? 'البيانات المرجعية للأداة' : 'Master Tool Data'} icon={Wrench} colorClass="text-secondary" />}
            {cat === 'other' && <AdminSectionHeader title={isRtl ? 'بيانات إضافية' : 'Additional Info'} sub={isRtl ? 'تفاصيل متنوعة' : 'Miscellaneous Details'} icon={Info} colorClass="text-secondary" />}
         </CardHeader>

         <CardContent className="p-8">
            {cat === 'heavy_machinery' && (
              <div className="space-y-8 animate-in slide-in-from-top-2">
                <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
                   <div className="space-y-1.5">
                      <Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'سنة التصنيع / الموديل' : 'Model Year'}</Label>
                      <Input 
                        type="text"
                        maxLength={4}
                        placeholder="YYYY"
                        value={form.manufacturingYear ?? ''} 
                        onChange={e => {
                          const val = e.target.value.replace(/\D/g, '').slice(0, 4);
                          setForm({...form, manufacturingYear: val});
                        }}
                        onBlur={() => {
                          const year = parseInt(form.manufacturingYear);
                          if (year && year < 1980) {
                            toast({ 
                              variant: "destructive", 
                              title: isRtl ? "سنة غير صالحة" : "Invalid Year", 
                              description: isRtl ? "سنة الصنع لا يمكن أن تكون قبل 1980." : "Manufacturing year cannot be before 1980."
                            });
                            setForm({...form, manufacturingYear: ''});
                          }
                        }}
                        className="h-12 rounded-xl border-2 font-black text-center bg-white" 
                      />
                   </div>
                   {form.isStreetLicensed ? (
                     <>
                        <div className="space-y-1.5"><Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'رقم اللوحة' : 'Plate Number'}</Label><Input value={form.plateNumber ?? ''} onChange={e => setForm({...form, plateNumber: e.target.value})} className="h-12 rounded-xl border-2 font-black" /></div>
                        <div className="space-y-1.5"><Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'رقم الدفتر' : 'Reg Number'}</Label><Input value={form.registrationNumber ?? ''} onChange={e => setForm({...form, registrationNumber: e.target.value})} className="h-12 rounded-xl border-2 font-bold" /></div>
                        <div className="space-y-1.5"><Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'انتهاء الدفتر' : 'Reg Expiry'}</Label><SmartDateInput value={form.registrationExpiry ?? ''} onChange={v => setForm({...form, registrationExpiry: v})} /></div>
                     </>
                   ) : (
                     <>
                        <div className="space-y-1.5"><Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'رقم الشاصي / السيريال' : 'Chassis / Serial'}</Label><Input value={form.chassisNumber ?? ''} onChange={e => setForm({...form, chassisNumber: e.target.value})} className="h-12 rounded-xl border-2 font-mono" /></div>
                        <div className="space-y-1.5"><Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'انتهاء الفحص الفني (3rd Party)' : '3rd Party Inspection'}</Label><SmartDateInput value={form.thirdPartyInspectionExpiry ?? ''} onChange={v => setForm({...form, thirdPartyInspectionExpiry: v})} /></div>
                        <div className="space-y-1.5"><Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'انتهاء تأمين الموقع' : 'Site Insurance Expiry'}</Label><SmartDateInput value={form.siteInsuranceExpiry ?? ''} onChange={v => setForm({...form, siteInsuranceExpiry: v})} /></div>
                     </>
                   )}
                </div>
                {form.isStreetLicensed && (
                   <div className="grid grid-cols-1 md:grid-cols-4 gap-6 pt-6 border-t border-slate-100">
                      <div className="space-y-1.5 md:col-start-4"><Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'انتهاء التأمين' : 'Insurance Expiry'}</Label><SmartDateInput value={form.insuranceExpiry ?? ''} onChange={v => setForm({...form, insuranceExpiry: v})} /></div>
                   </div>
                )}
              </div>
            )}

            {cat === 'vehicle' && (
              <div className="space-y-8 animate-in slide-in-from-top-2">
                 <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
                    <div className="space-y-1.5">
                       <Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'سنة التصنيع / الموديل' : 'Model Year'}</Label>
                       <Input 
                        type="text"
                        maxLength={4}
                        placeholder="YYYY"
                        value={form.manufacturingYear ?? ''} 
                        onChange={e => {
                          const val = e.target.value.replace(/\D/g, '').slice(0, 4);
                          setForm({...form, manufacturingYear: val});
                        }}
                        onBlur={() => {
                          const year = parseInt(form.manufacturingYear);
                          if (year && year < 1980) {
                            toast({ 
                              variant: "destructive", 
                              title: isRtl ? "سنة غير صالحة" : "Invalid Year", 
                              description: isRtl ? "سنة الصنع لا يمكن أن تكون قبل 1980." : "Manufacturing year cannot be before 1980."
                            });
                            setForm({...form, manufacturingYear: ''});
                          }
                        }}
                        className="h-12 rounded-xl border-2 font-black text-center bg-white" 
                      />
                    </div>
                    <div className="space-y-1.5"><Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'رقم اللوحة' : 'Plate Number'}</Label><Input value={form.plateNumber ?? ''} onChange={e => setForm({...form, plateNumber: e.target.value})} className="h-12 rounded-xl border-2 font-black" /></div>
                    <div className="space-y-1.5"><Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'رقم الدفتر' : 'Reg Number'}</Label><Input value={form.registrationNumber ?? ''} onChange={e => setForm({...form, registrationNumber: e.target.value})} className="h-12 rounded-xl border-2" /></div>
                    <div className="space-y-1.5"><Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'رقم الشاصي (VIN)' : 'Chassis VIN'}</Label><Input value={form.chassisNumber ?? ''} onChange={e => setForm({...form, chassisNumber: e.target.value})} className="h-12 rounded-xl border-2 font-mono" /></div>
                 </div>
                 <div className="grid grid-cols-1 md:grid-cols-3 gap-6 pt-6 border-t border-slate-100">
                    <div className="space-y-1.5"><Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'انتهاء الدفتر' : 'Reg Expiry'}</Label><SmartDateInput value={form.registrationExpiry ?? ''} onChange={v => setForm({...form, registrationExpiry: v})} /></div>
                    <div className="space-y-2">
                       <Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'نوع التأمين' : 'Insurance Type'}</Label>
                       <Select value={form.insuranceType} onValueChange={v => setForm({...form, insuranceType: v})}>
                          <SelectTrigger className="h-12 rounded-xl border-2"><SelectValue /></SelectTrigger>
                          <SelectContent className="rounded-xl">
                             <SelectItem value="comprehensive">{isRtl ? 'شامل (Full)' : 'Comprehensive'}</SelectItem>
                             <SelectItem value="third_party">{isRtl ? 'ضد الغير (TPL)' : 'Third Party'}</SelectItem>
                          </SelectContent>
                       </Select>
                    </div>
                    <div className="space-y-1.5"><Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'انتهاء التأمين' : 'Insurance Expiry'}</Label><SmartDateInput value={form.insuranceExpiry ?? ''} onChange={v => setForm({...form, insuranceExpiry: v})} /></div>
                 </div>
              </div>
            )}

            {cat === 'stationary' && (
              <div className="grid grid-cols-1 md:grid-cols-5 gap-6 animate-in slide-in-from-top-2">
                 <div className="space-y-1.5">
                    <Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'سنة التصنيع' : 'Model Year'}</Label>
                    <Input 
                        type="text"
                        maxLength={4}
                        placeholder="YYYY"
                        value={form.manufacturingYear ?? ''} 
                        onChange={e => {
                          const val = e.target.value.replace(/\D/g, '').slice(0, 4);
                          setForm({...form, manufacturingYear: val});
                        }}
                        onBlur={() => {
                          const year = parseInt(form.manufacturingYear);
                          if (year && year < 1980) {
                            toast({ 
                              variant: "destructive", 
                              title: isRtl ? "سنة غير صالحة" : "Invalid Year", 
                              description: isRtl ? "سنة الصنع لا يمكن أن تكون قبل 1980." : "Manufacturing year cannot be before 1980."
                            });
                            setForm({...form, manufacturingYear: ''});
                          }
                        }}
                        className="h-12 rounded-xl border-2 font-black text-center bg-white" 
                      />
                 </div>
                 <div className="space-y-1.5"><Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'الرقم التسلسلي' : 'Serial No'}</Label><Input value={form.serialNumber ?? ''} onChange={e => setForm({...form, serialNumber: e.target.value})} className="h-12 rounded-xl border-2 font-mono" /></div>
                 <div className="space-y-1.5"><Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'القدرة (KVA/HP)' : 'Capacity'}</Label><Input value={form.capacity ?? ''} onChange={e => setForm({...form, capacity: e.target.value})} className="h-12 rounded-xl border-2 font-black text-secondary" /></div>
                 <div className="space-y-1.5"><Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'موعد الصيانة القادم' : 'Next Service'}</Label><SmartDateInput value={form.nextServiceDate ?? ''} onChange={v => setForm({...form, nextServiceDate: v})} /></div>
                 <div className="space-y-1.5"><Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'انتهاء شهادة السلامة' : 'Safety Cert'}</Label><SmartDateInput value={form.safetyCertExpiry ?? ''} onChange={v => setForm({...form, safetyCertExpiry: v})} /></div>
              </div>
            )}

            {cat === 'hand_tool' && (
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6 animate-in slide-in-from-top-2">
                 <div className="space-y-1.5"><Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'الرقم التسلسلي (SN)' : 'Serial No'}</Label><Input value={form.serialNumber ?? ''} onChange={e => setForm({...form, serialNumber: e.target.value})} className="h-12 rounded-xl border-2 font-mono" /></div>
                 <div className="space-y-1.5"><Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'الماركة / الموديل' : 'Brand / Model'}</Label><Input value={form.brandModel ?? ''} onChange={e => setForm({...form, brandModel: e.target.value})} className="h-12 rounded-xl border-2 font-bold" placeholder="e.g. Bosch / Makita" /></div>
                 <div className="space-y-2">
                    <Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'الحالة الفنية' : 'Condition'}</Label>
                    <Select value={form.toolCondition} onValueChange={(v: ToolCondition) => setForm({...form, toolCondition: v})}>
                       <SelectTrigger className="h-12 rounded-xl border-2 font-bold"><SelectValue /></SelectTrigger>
                       <SelectContent className="rounded-xl">
                          <SelectItem value="new" className="font-bold">{isRtl ? 'جديدة (New)' : 'New'}</SelectItem>
                          <SelectItem value="used_good" className="font-bold">{isRtl ? 'مستعملة - حالة جيدة' : 'Used - Good'}</SelectItem>
                          <SelectItem value="under_maintenance" className="font-bold text-rose-600">{isRtl ? 'تحت الصيانة' : 'Maintenance'}</SelectItem>
                       </SelectContent>
                    </Select>
                 </div>
              </div>
            )}

            {cat === 'other' && (
              <div className="animate-in fade-in">
                 <Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'الرقم المرجعي / الوصف' : 'Reference / Description'}</Label>
                 <Input value={form.notes ?? ''} onChange={e => setForm({...form, notes: e.target.value})} className="h-12 rounded-xl border-2 mt-2" />
              </div>
            )}
         </CardContent>
      </Card>

      {/* 3. الملكية والتمويل */}
      <Card className="border-0 shadow-xl rounded-[2.5rem] bg-white overflow-hidden ring-1 ring-black/5">
        <CardHeader className="bg-white p-8 border-b">
           <div className="flex items-center justify-between">
              <AdminSectionHeader title={isRtl ? 'الملكية والتمويل' : 'Ownership & Financing'} sub={isRtl ? 'حالة التملك والالتزام المالي' : 'Possession Status'} icon={ShieldCheck} />
              <div className="flex items-center gap-4 bg-slate-50 px-6 py-2 rounded-full border-2 shadow-inner">
                 <Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'مملوكة' : 'Owned'}</Label>
                 <Switch checked={isOwned} onCheckedChange={v => setForm({...form, ownershipType: v ? 'owned' : 'rented'})} />
              </div>
           </div>
        </CardHeader>
        <CardContent className="p-8 space-y-8">
           <div className="grid grid-cols-1 md:grid-cols-2 gap-8 text-start">
              {isOwned ? (
                 <div className="flex items-center justify-between p-6 bg-primary/5 rounded-[2rem] border-2 border-primary/10">
                    <div className="space-y-1">
                       <Label className="font-black text-sm text-slate-800">{isRtl ? 'هل المعدة ممولة (أقساط)؟' : 'Is it Financed?'}</Label>
                       <p className="text-[9px] text-slate-400 font-bold uppercase tracking-tight">Linked to Bank/Finance Co.</p>
                    </div>
                    <Switch checked={form.isFinanced ?? false} onCheckedChange={v => setForm({...form, isFinanced: v})} />
                 </div>
              ) : (
                 <div className="space-y-2">
                    <Label className="text-[10px] font-black uppercase text-slate-400 tracking-widest">{isRtl ? 'المورد المؤجر' : 'Renting Supplier'}</Label>
                    <Select value={form.supplierId ?? ''} onValueChange={v => {
                       const s = suppliers?.find((x:any) => x.id === v);
                       setForm({...form, supplierId: v, supplierName: s?.name || ''});
                    }}>
                       <SelectTrigger className="h-12 rounded-xl border-2 font-bold bg-white"><SelectValue placeholder="..." /></SelectTrigger>
                       <SelectContent className="rounded-xl">{suppliers?.map((s:any) => <SelectItem key={s.id} value={s.id!}>{s.name}</SelectItem>)}</SelectContent>
                    </Select>
                 </div>
              )}
           </div>

           {form.isFinanced && isOwned && (
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6 p-8 bg-slate-50/50 rounded-[2rem] border-2 border-white shadow-inner animate-in zoom-in-95 text-start">
                 <div className="space-y-1.5"><Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'جهة التمويل' : 'Financier'}</Label><Input value={form.financierName ?? ''} onChange={e => setForm({...form, financierName: e.target.value})} className="h-12 rounded-xl border-2 bg-white" placeholder={isRtl ? "البنك أو شركة التمويل" : "Bank Name"} /></div>
                 <div className="space-y-1.5"><Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'القسط الشهري (KWD)' : 'Installment'}</Label><Input type="number" value={form.monthlyInstallment ?? ''} onChange={e => setForm({...form, monthlyInstallment: e.target.value})} className="h-12 rounded-xl border-2 bg-white font-black text-emerald-600" /></div>
                 <div className="space-y-1.5"><Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'يوم الاستحقاق' : 'Due Day'}</Label><Input type="number" min="1" max="31" value={form.installmentDay ?? ''} onChange={e => setForm({...form, installmentDay: e.target.value})} className="h-12 rounded-xl border-2 bg-white font-black text-center" /></div>
              </div>
           )}
        </CardContent>
      </Card>

      {/* 4. المعالجة المالية */}
      <Card className="border-0 shadow-xl rounded-[2.5rem] bg-white overflow-hidden ring-1 ring-black/5">
        <CardHeader className="bg-slate-50/50 p-8 border-b">
           <AdminSectionHeader title={isRtl ? 'المعطيات المالية والتشغيلية' : 'Finance & Rates'} sub={isRtl ? 'تحديد تعرفة الساعة وتكاليف التشغيل' : 'Cost Recovery Metrics'} icon={Calculator} />
        </CardHeader>
        <CardContent className="p-8 space-y-8 text-start">
           {isOwned ? (
             <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                <div className="space-y-2"><Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'سعر شراء الأصل' : 'Purchase Cost'}</Label><Input type="number" value={form.purchaseCost ?? ''} onChange={e => setForm({...form, purchaseCost: e.target.value})} className="h-12 rounded-xl border-2 font-black text-emerald-600 bg-white" /></div>
                <div className="space-y-2"><Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'القيمة التخريدية' : 'Salvage Value'}</Label><Input type="number" value={form.salvageValue ?? ''} onChange={e => setForm({...form, salvageValue: e.target.value})} className="h-12 rounded-xl border-2 font-black bg-white" placeholder="1" /></div>
                <div className="space-y-2">
                    <Label className="text-[10px] font-black uppercase text-primary flex items-center gap-2">
                        <Clock className="h-4 w-4" /> {isRtl ? 'تعرفة التشغيل بالساعة' : 'Operating Rate'}
                    </Label>
                    <Input type="number" step="0.001" value={form.hourlyDepreciationRate ?? ''} onChange={e => setForm({...form, hourlyDepreciationRate: e.target.value})} className="h-12 rounded-xl border-2 font-black text-primary bg-white" />
                </div>
             </div>
           ) : (
             <div className="grid grid-cols-1 md:grid-cols-2 gap-8 p-8 bg-slate-50 rounded-[2rem] border-2 border-white shadow-inner text-start">
                <div className="space-y-2">
                   <Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'أساس تعرفة الاستئجار' : 'Rental Basis'}</Label>
                   <Select value={form.costMethod ?? 'hourly'} onValueChange={(v: any) => setForm({...form, costMethod: v})}>
                      <SelectTrigger className="h-12 rounded-xl border-2 font-bold bg-white"><SelectValue placeholder="..." /></SelectTrigger>
                      <SelectContent className="rounded-xl">
                         <SelectItem value="hourly" className="font-bold">{isRtl ? 'بالساعة (KWD/HR)' : 'Hourly'}</SelectItem>
                         <SelectItem value="daily" className="font-bold">{isRtl ? 'يومي (KWD/Day)' : 'Daily'}</SelectItem>
                         <SelectItem value="monthly" className="font-bold">{isRtl ? 'شهري (KWD/Month)' : 'Monthly'}</SelectItem>
                      </SelectContent>
                   </Select>
                </div>
                <div className="space-y-2">
                   <Label className="text-[10px] font-black uppercase text-slate-400">{isRtl ? 'قيمة الاستئجار' : 'Rental Value'}</Label>
                   <Input type="number" step="0.001" value={form.costValue ?? ''} onChange={e => setForm({...form, costValue: e.target.value})} className="h-12 rounded-xl border-2 font-black text-xl text-orange-600 bg-white" />
                </div>
             </div>
           )}
        </CardContent>
      </Card>

      <div className="flex justify-end gap-4 pt-10 px-4">
         <Button variant="outline" type="button" onClick={() => window.history.back()} className="h-14 px-10 rounded-full font-bold border-2 bg-white text-slate-600 shadow-sm">{isRtl ? 'إلغاء' : 'Cancel'}</Button>
         <button 
           type="button"
           onClick={handlePreSubmit} 
           disabled={loading || !form.name || !form.code}
           className="h-14 px-24 rounded-full bg-primary text-white font-black text-xl shadow-xl shadow-primary/20 hover:scale-[1.02] active:scale-[0.98] transition-all flex items-center gap-3 border-b-8 border-[#f57c00]"
         >
            {loading ? <Loader2 className="animate-spin h-6 w-6" /> : <Save className="h-6 w-6" />}
            {isRtl ? 'اعتماد وحفظ الأصل' : 'Commit Asset'}
         </button>
      </div>
    </div>
  );
}
