'use client';

import { getTenantPath } from '@/lib/utils';

export const paths = {
  globalUser: (uid: string) => `global_users/${uid}`,
  company: (companyId: string) => `companies/${companyId}`,
  invitations: (companyId: string) => getTenantPath(companyId, 'invitations'),
  departments: (companyId: string) => getTenantPath(companyId, 'departments'),
  jobs: (companyId: string, deptId: string) => `${getTenantPath(companyId, 'departments')}/${deptId}/jobs`,
  roles: (companyId: string) => getTenantPath(companyId, 'roles'),
  governorates: (companyId: string) => getTenantPath(companyId, 'governorates'),
  areas: (companyId: string, govId: string) => `${getTenantPath(companyId, 'governorates')}/${govId}/areas`,
  unitTypes: (companyId: string) => getTenantPath(companyId, 'unitTypes'),
  paymentMethods: (companyId: string) => getTenantPath(companyId, 'paymentMethods'),
  paymentConditionTypes: (companyId: string) => getTenantPath(companyId, 'paymentConditionTypes'),
  milestoneTimingTypes: (companyId: string) => getTenantPath(companyId, 'milestoneTimingTypes'),
  itemCategories: (companyId: string) => getTenantPath(companyId, 'itemCategories'),
  costTypeCategories: (companyId: string) => getTenantPath(companyId, 'costTypeCategories'),
  meetingRooms: (companyId: string) => getTenantPath(companyId, 'meetingRooms'),
  serviceTypes: (companyId: string) => getTenantPath(companyId, 'serviceTypes'),
  leads: (companyId: string) => getTenantPath(companyId, 'leads'),
  clients: (companyId: string) => getTenantPath(companyId, 'clients'),
  clientHistory: (companyId: string, clientId: string) => `${getTenantPath(companyId, 'clients')}/${clientId}/history`,
  employees: (companyId: string) => getTenantPath(companyId, 'employees'),
  applications: (companyId: string) => getTenantPath(companyId, 'applications'),
  leaveRequests: (companyId: string) => getTenantPath(companyId, 'leaveRequests'),
  permissionRequests: (companyId: string) => getTenantPath(companyId, 'permissionRequests'),
  attendance: (companyId: string) => getTenantPath(companyId, 'attendance'),
  payroll: (companyId: string) => getTenantPath(companyId, 'payroll'),
  warehouses: (companyId: string) => getTenantPath(companyId, 'warehouses'),
  inventoryItems: (companyId: string) => getTenantPath(companyId, 'inventoryItems'),
  inventoryTransactions: (companyId: string) => getTenantPath(companyId, 'inventoryTransactions'), 
  assetAssignments: (companyId: string) => getTenantPath(companyId, 'assetAssignments'),
  suppliers: (companyId: string) => getTenantPath(companyId, 'suppliers'),
  purchaseOrders: (companyId: string) => getTenantPath(companyId, 'purchaseOrders'),
  poItems: (companyId: string, poId: string) => `${getTenantPath(companyId, 'purchaseOrders')}/${poId}/items`,
  activityTypes: (companyId: string) => getTenantPath(companyId, 'activityTypes'),
  services: (companyId: string, actId: string) => `${getTenantPath(companyId, 'activityTypes')}/${actId}/services`,
  subServices: (companyId: string, actId: string, srvId: string) => `${getTenantPath(companyId, 'activityTypes')}/${actId}/services/${srvId}/subServices`,
  technicalStages: (companyId: string, actId: string, srvId: string, subId: string) => `${getTenantPath(companyId, 'activityTypes')}/${actId}/services/${srvId}/subServices/${subId}/stages`,
  transactions: (companyId: string) => getTenantPath(companyId, 'transactions'),
  transactionStages: (companyId: string, tId: string) => `${getTenantPath(companyId, 'transactions')}/${tId}/stageInstances`,
  transactionTimeline: (companyId: string, tId: string) => `${getTenantPath(companyId, 'transactions')}/${tId}/timeline`,
  transactionComments: (companyId: string, tId: string) => `${getTenantPath(companyId, 'transactions')}/${tId}/comments`,
  boqReferenceNodes: (companyId: string) => getTenantPath(companyId, 'boqReferenceNodes'),
  quotationTemplates: (companyId: string) => getTenantPath(companyId, 'quotationTemplates'),
  contractTemplates: (companyId: string) => getTenantPath(companyId, 'contractTemplates'),
  boqTemplates: (companyId: string) => getTenantPath(companyId, 'boqTemplates'),
  boqTemplateItems: (companyId: string, templateId: string) => `${getTenantPath(companyId, 'boqTemplates')}/${templateId}/items`,
  quotations: (companyId: string) => getTenantPath(companyId, 'quotations'),
  contracts: (companyId: string) => getTenantPath(companyId, 'contracts'),
  boqs: (companyId: string) => getTenantPath(companyId, 'boqs'),
  boqItems: (companyId: string, boqId: string) => `${getTenantPath(companyId, 'boqs')}/${boqId}/items`,
  boqVariations: (companyId: string, boqId: string) => `${getTenantPath(companyId, 'boqs')}/${boqId}/variations`,
  boqVariationItems: (companyId: string, boqId: string, voId: string) => `${getTenantPath(companyId, 'boqs')}/${boqId}/variations/${voId}/items`,
  executions: (companyId: string) => getTenantPath(companyId, 'executions'),
  appointments: (companyId: string) => getTenantPath(companyId, 'appointments'),
  fieldVisits: (companyId: string, transactionId: string) => `${getTenantPath(companyId, 'transactions')}/${transactionId}/fieldVisits`,
  
  // New Paths for IPCs and Rate Cards
  ipcs: (companyId: string) => getTenantPath(companyId, 'ipcs'),
  costRateCards: (companyId: string) => getTenantPath(companyId, 'costRateCards'),
};
