'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
  lang: Language;
  dir: 'rtl' | 'ltr';
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  ar: {
    dashboard: 'لوحة التحكم',
    crm: 'العملاء والفرص',
    projects: 'المشاريع والمهام',
    accounting: 'المحاسبة والمالية',
    hr: 'الموارد البشرية',
    procurement: 'المشتريات والتوريد',
    inventory: 'المخازن والعهد',
    checklists: 'مركز المراجع',
    reports: 'التقارير التنفيذية',
    ai: 'ذكاء Nova AI',
    settings: 'الإعدادات',
    workspace: 'مساحة العمل',
    switchLang: 'English',
    logout: 'تسجيل الخروج',
    profile: 'الملف الشخصي',
    billing: 'الفواتير',
    save: 'حفظ',
    saved: 'تم الحفظ',
    error: 'خطأ',
    edit: 'تعديل',
    deleted: 'تم الحذف',
    entryAdded: 'تمت العملية بنجاح.',
    saveFailed: 'فشل في الاتصال بالسحاب.',
    confirmDelete: 'تأكيد الحذف؟',
    active: 'نشط',
    completed: 'مكتمل',
    suspended: 'موقوف',
    'on-hold': 'انتظار',
    search: 'بحث...',
    newProject: 'مشروع جديد',
    startProject: 'بدء المشروع',
    name: 'الاسم',
    budget: 'الميزانية',
    status: 'الحالة',
    project: 'المشروع',
    govs: 'المحافظة',
    value: 'القيمة',
    summary: 'الملخص',
    orgRef: 'الهيكل التنظيمي',
    techRef: 'المسارات الفنية',
    geoRef: 'الجغرافيا',
    rolesRef: 'الأدوار والصلاحيات',
    systemSetup: 'التهيئة',
    newDept: 'قسم جديد',
    newGov: 'محافظة جديدة',
    newArea: 'منطقة جديدة',
    newActivity: 'نشاط جديد',
    newService: 'خدمة جديدة',
    newPath: 'مسار جديد',
    addStage: 'إضافة مرحلة',
    editStage: 'تعديل مرحلة',
    nextStages: 'المراحل اللاحقة',
    technicalLink: 'الارتباط الفني',
    operationalPath: 'المسار التشغيلي',
    totalStages: 'إجمالي المراحل',
    expectedValue: 'القيمة المتوقعة',
    addLead: 'إضافة عميل',
    companyIdentity: 'الهوية',
    companyProfile: 'بيانات المنشأة',
    logo: 'الشعار',
    header: 'ترويسة المستند',
    footer: 'تذييل المستند',
    licenseExpiry: 'انتهاء الترخيص',
    laborExpiry: 'اعتماد الشؤون',
    address: 'العنوان',
    commercialRegistry: 'السجل التجاري',
    phone: 'الهاتف',
    email: 'البريد',
    saveChanges: 'حفظ التعديلات',
    manageCompanyData: 'إدارة الهوية والوثائق الرسمية',
    writeText: 'نص حر',
    team: 'الفريق',
    employees: 'الموظفين',
    operationalCompliance: 'الامتثال',
    docAnalysis: 'تحليل الوثائق',
    uploadDoc: 'رفع مستند',
    analyzeNow: 'تحليل ذكي',
    complianceData: 'بيانات المستند',
    complianceNotes: 'ملاحظات قانونية',
    employeeName: 'اسم الموظف',
    docType: 'النوع',
    docNumber: 'رقم المستند',
    issuer: 'جهة الإصدار',
    changeRole: 'تغيير الدور',
    assignRole: 'تعيين دور',
    noEmployees: 'لا يوجد سجلات.',
    joinDate: 'تاريخ التعيين',
    workHours: 'ساعات العمل',
    generalWorkingHours: 'الدوام العام',
    architecturalWorkingHours: 'المعماري',
    holidays: 'العطلات',
    halfDay: 'نصف دوام',
    ramadanSchedule: 'جدول رمضان',
    morningStart: 'بداية الصباح',
    morningEnd: 'نهاية الصباح',
    eveningStart: 'بداية المساء',
    eveningEnd: 'نهاية المساء',
    slotDuration: 'المدة (دقيقة)',
    bufferTime: 'الفاصل (دقيقة)',
    saveAllRules: 'حفظ القواعد',
    halfDayMode: 'النظام',
    morningOnly: 'صباحي فقط',
    customEndTime: 'إغلاق مخصص',
    ramadanPeriod: 'فترة رمضان',
    enabled: 'مفعل',
    startDate: 'من تاريخ',
    endDate: 'إلى تاريخ',
    startTime: 'بداية',
    endTime: 'نهاية',
    workHoursDesc: 'إدارة الورديات والعطلات الأسبوعية.',
    backToSettings: 'رجوع',
    singleShift: 'وردية واحدة',
    doubleShift: 'ورديتين',
    ramadanMode: 'نظام الدوام',
    periodStart: 'بداية',
    periodEnd: 'نهاية',
    addKuwaitHolidays: 'عطلات الكويت 2026',
    personalInfo: 'بياناتي',
    accountSecurity: 'الأمان',
    username: 'المستخدم',
    displayName: 'الاسم الكامل',
    currentRole: 'الدور',
    changePassword: 'تغيير الباسورد',
    passwordDesc: 'حماية حسابك تبدأ بكلمة مرور قوية.',
    lastLogin: 'آخر دخول',
    gratuity: 'مكافأة نهاية الخدمة',
    leaves: 'الإجازات',
    permissions: 'الاستئذانات',
    attendance: 'الحضور والانصراف',
    payroll: 'الرواتب',
    hrReports: 'تقارير الموارد البشرية',
    Sunday: 'الأحد',
    Monday: 'الاثنين',
    Tuesday: 'الثلاثاء',
    Wednesday: 'الأربعاء',
    Thursday: 'الخميس',
    Friday: 'الجمعة',
    Saturday: 'السبت',
    leads: 'الفرص البيعية',
    clients: 'قاعدة العملاء',
    projectExecution: 'تنفيذ المشاريع',
    projectReports: 'تقارير فنية',
    journalEntries: 'قيود اليومية',
    chartOfAccounts: 'دليل الحسابات',
    suppliers: 'الموردين',
    purchaseOrders: 'أوامر الشراء',
    supplierQuotes: 'عروض الموردين',
    quoteAnalysis: 'التحليل الذكي للعروض',
    warehouses: 'إدارة المخازن',
    fieldAssets: 'العهد الميدانية',
    operationalReports: 'تقارير العمليات',
    financialReports: 'تقارير مالية',
    bankStatement: 'كشف الحساب',
    ledger: 'دفتر الأستاذ',
    smartReconciliation: 'مطابقة ذكية بالذكاء الاصطناعي',
    reconReport: 'تقرير المطابقة',
    suggestedMatches: 'المطابقات المقترحة',
    payslip: 'قسيمة الراتب',
    gratuityCalculator: 'حاسبة المستحقات',
    importAttendance: 'استيراد البصمة',
    employeeDossier: 'الملف الشامل',
    pending: 'قيد الانتظار',
    approved: 'معتمد',
    rejected: 'مرفوض',
    paid: 'مدفوع',
    reviewed: 'تمت المراجعة',
    late_arrival: 'حضور متأخر',
    early_departure: 'انصراف مبكر',
    annual: 'سنوية',
    sick: 'مرضية',
    emergency: 'اضطرارية',
    unpaid: 'بدون راتب'
  },
  en: {
    dashboard: 'Dashboard',
    crm: 'CRM',
    projects: 'Projects',
    accounting: 'Accounting',
    hr: 'Human Resources',
    procurement: 'Procurement & Supply',
    inventory: 'Inventory',
    checklists: 'Reference Hub',
    reports: 'Reports',
    ai: 'Nova AI',
    settings: 'Settings',
    workspace: 'Workspace',
    switchLang: 'العربية',
    logout: 'Logout',
    profile: 'Profile',
    billing: 'Billing',
    save: 'Save',
    saved: 'Saved',
    error: 'Error',
    edit: 'Edit',
    deleted: 'Deleted',
    entryAdded: 'Operation successful.',
    saveFailed: 'Sync failed.',
    confirmDelete: 'Confirm delete?',
    active: 'Active',
    completed: 'Completed',
    suspended: 'Suspended',
    'on-hold': 'On Hold',
    search: 'Search...',
    newProject: 'New Project',
    startProject: 'Launch',
    name: 'Name',
    budget: 'Budget',
    status: 'Status',
    project: 'Project',
    govs: 'Gov',
    value: 'Value',
    summary: 'Summary',
    orgRef: 'Organization',
    techRef: 'Technical',
    geoRef: 'Geography',
    rolesRef: 'Roles',
    systemSetup: 'Setup',
    newDept: 'New Dept',
    newGov: 'New Gov',
    newArea: 'New Area',
    newActivity: 'New Activity',
    newService: 'New Service',
    newPath: 'New Path',
    addStage: 'Add Stage',
    editStage: 'Edit Stage',
    nextStages: 'Next Stages',
    technicalLink: 'Technical Link',
    operationalPath: 'Ops Path',
    totalStages: 'Total Stages',
    expectedValue: 'Expectation',
    addLead: 'Add Lead',
    companyIdentity: 'Identity',
    companyProfile: 'Profile',
    logo: 'Logo',
    header: 'Doc Header',
    footer: 'Doc Footer',
    licenseExpiry: 'License Expiry',
    laborExpiry: 'Labor Expiry',
    address: 'Address',
    commercialRegistry: 'Registry #',
    phone: 'Phone',
    email: 'Email',
    saveChanges: 'Save Changes',
    manageCompanyData: 'Manage company assets',
    writeText: 'Free Text',
    team: 'Team',
    employees: 'Employees',
    operationalCompliance: 'Compliance',
    docAnalysis: 'Analysis',
    uploadDoc: 'Upload',
    analyzeNow: 'AI Analyze',
    complianceData: 'Extracted',
    complianceNotes: 'Legal Notes',
    employeeName: 'Name',
    docType: 'Type',
    docNumber: 'Number',
    issuer: 'Issuer',
    changeRole: 'Role change',
    assignRole: 'Assign',
    noEmployees: 'No records.',
    joinDate: 'Joined At',
    workHours: 'Work Hours',
    generalWorkingHours: 'General',
    architecturalWorkingHours: 'Architectural',
    holidays: 'Holidays',
    halfDay: 'Half-Day',
    ramadanSchedule: 'Ramadan',
    morningStart: 'Morning Start',
    morningEnd: 'Morning End',
    eveningStart: 'Evening Start',
    eveningEnd: 'Morning End',
    slotDuration: 'Duration (min)',
    bufferTime: 'Buffer (min)',
    saveAllRules: 'Save Rules',
    halfDayMode: 'Mode',
    morningOnly: 'Morning Only',
    customEndTime: 'Custom End',
    ramadanPeriod: 'Ramadan Period',
    enabled: 'Enabled',
    startDate: 'From',
    endDate: 'To',
    startTime: 'Start',
    endTime: 'End',
    workHoursDesc: 'Manage shifts and weekends.',
    backToSettings: 'Back',
    singleShift: 'Single Shift',
    doubleShift: 'Double Shift',
    ramadanMode: 'Mode',
    periodStart: 'Start',
    periodEnd: 'End',
    addKuwaitHolidays: 'Kuwait 2026',
    personalInfo: 'Personal',
    accountSecurity: 'Security',
    username: 'Username',
    displayName: 'Full Name',
    currentRole: 'Role',
    changePassword: 'Password',
    passwordDesc: 'Protect your access.',
    lastLogin: 'Last Login',
    gratuity: 'Gratuity',
    leaves: 'Leaves',
    permissions: 'Permissions',
    attendance: 'Attendance',
    payroll: 'Payroll',
    hrReports: 'HR Reports',
    Sunday: 'Sunday',
    Monday: 'Monday',
    Tuesday: 'Tuesday',
    Wednesday: 'Wednesday',
    Thursday: 'Thursday',
    Friday: 'Friday',
    Saturday: 'Saturday',
    leads: 'Sales Leads',
    clients: 'Clients Database',
    projectExecution: 'Execution',
    projectReports: 'Engineering Reports',
    journalEntries: 'Journal Entries',
    chartOfAccounts: 'COA',
    suppliers: 'Suppliers',
    purchaseOrders: 'LPO',
    supplierQuotes: 'Quotes',
    quoteAnalysis: 'AI Analysis',
    warehouses: 'Warehouse',
    fieldAssets: 'Field Assets',
    operationalReports: 'Ops Reports',
    financialReports: 'Fin Reports',
    bankStatement: 'Bank Statement',
    ledger: 'General Ledger',
    smartReconciliation: 'AI Smart Recon',
    reconReport: 'Recon Report',
    suggestedMatches: 'Suggested Matches',
    payslip: 'Payslip',
    gratuityCalculator: 'Gratuity Calc',
    importAttendance: 'Import Biometric',
    employeeDossier: 'Full Dossier',
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    paid: 'Paid',
    reviewed: 'Reviewed',
    late_arrival: 'Late Arrival',
    early_departure: 'Early Departure',
    annual: 'Annual',
    sick: 'Sick',
    emergency: 'Emergency',
    unpaid: 'Unpaid'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>('ar');

  useEffect(() => {
    const savedLang = localStorage.getItem('lang') as Language || 'ar';
    setLang(savedLang);
  }, []);

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem('lang', newLang);
    document.documentElement.lang = newLang;
    document.documentElement.dir = newLang === 'ar' ? 'rtl' : 'ltr';
  };

  const t = (key: string) => translations[lang][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, dir: lang === 'ar' ? 'rtl' : 'ltr', setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
