'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
  lang: Language;
  dir: 'rtl' | 'ltr';
  isRtl: boolean;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
  tSafe: (key: string, fallbackAr: string, fallbackEn?: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  ar: {
    // --- Common ---
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.add': 'إضافة',
    'common.close': 'إغلاق',
    'common.filter': 'تصفية',
    'common.confirm': 'تأكيد',
    'common.search': 'بحث...',
    'common.status': 'الحالة',
    'common.date': 'التاريخ',
    'common.name': 'الاسم',
    'common.nameAr': 'الاسم (عربي)',
    'common.nameEn': 'الاسم (EN)',
    'common.amount': 'المبلغ',
    'common.notes': 'الملاحظات',
    'common.error': 'خطأ في العملية',
    'common.saved': 'تم الحفظ بنجاح',
    'common.noResults': 'لا يوجد نتائج مطابقة',
    'common.overview': 'نظرة عامة',
    'common.reason': 'السبب',
    'common.company': 'الشركة',
    'common.email': 'البريد الإلكتروني',
    'common.unit': 'الوحدة',
    'common.quantity': 'الكمية',
    'common.total': 'الإجمالي',
    'common.days': 'أيام',
    'common.print': 'طباعة',
    'common.editItems': 'تعديل البنود',
    'common.quotation': 'عرض سعر',
    'common.unexpectedError': 'حدث خطأ غير متوقع',
    'common.addLabel': 'إضافة بند',
    'common.labor': 'العمالة والموارد البشرية',
    'common.loadFromGroup': 'تحميل من طاقم',
    'common.equipment': 'المعدات والآليات',
    'common.deleted': 'تم الحذف بنجاح',
    'common.confirmDelete': 'تأكيد الحذف',
    'common.retry': 'إعادة المحاولة',
    'common.back': 'العودة للقائمة',
    'common.response': 'رد المسؤول',
    'common.photosUploaded': 'تم رفع الصور',
    'common.saveChanges': 'حفظ التغييرات',
    'common.description': 'الوصف',
    'common.isActive': 'نشط',
    'common.code': 'الكود المرجعي',
    'common.alert': 'تنبيه',
    'common.viewAll': 'عرض الكل',
    'common.pending': 'معلق',
    'common.getStarted': 'ابدأ الآن',
    'common.records': 'سجلات',

    // --- Dashboard ---
    'dashboard': 'لوحة التحكم',
    'dashboard.title': 'نظرة عامة على العمليات',
    'dashboard.export': 'تصدير التقارير',
    'dashboard.missions': 'المهمات المتأخرة',
    'dashboard.recent': 'آخر النشاطات',
    'dashboard.stats.revenue': 'إجمالي الإيرادات',
    'dashboard.stats.activeProjects': 'المشاريع الجارية',
    'dashboard.stats.workforce': 'القوى العاملة',
    'dashboard.stats.completion': 'معدل الإنجاز',
    'dashboard.units.kwd': 'د.ك',
    'dashboard.units.new': 'جديد',
    'dashboard.units.present': 'حاضر',
    'dashboard.units.yr': 'سنة',
    'dashboard.chart.revenue': 'الإيرادات',
    'dashboard.chart.expenses': 'المصروفات',
    'dashboard.recent.quoteApproved': 'تم اعتماد عرض سعر',
    'dashboard.recent.attendanceLogged': 'تم تسجيل الحضور',
    'dashboard.recent.paymentVoucher': 'سند صرف مالي',

    // --- CRM & Clients ---
    'crm': 'العملاء والفرص',
    'crm.description': 'إدارة الفرص البيعية والمتابعة التجارية للعملاء',
    'crm.newLead': 'إضافة فرصة جديدة',
    'crm.leadValue': 'القيمة المتوقعة',
    'leads': 'الفرص والعملاء',
    'clients': 'العملاء',
    'clients.title': 'سجل العملاء المعتمد',
    'clients.registerNew': 'تسجيل عميل جديد',
    'clients.registerNewDesc': 'فتح ملف تجاري جديد لربطه بالمعاملات الفنية',
    'clients.editProfile': 'تعديل بيانات العميل',
    'clients.updateSuccess': 'تم تحديث بيانات العميل بنجاح.',
    'clients.unauthorizedEdit': 'لا تملك صلاحية تعديل بيانات العملاء.',
    'clients.table.profile': 'بيان العميل',
    'clients.table.staff': 'المهندس المسؤول',
    'clients.table.contact': 'الاتصال',
    'clients.details.transactions': 'المعاملات الفنية والمالية',
    'clients.details.location': 'رادار الموقع والعنوان',
    'clients.details.history': 'سجل تفاعل العميل',
    'clients.form.identity': 'البيانات الأساسية والقانونية',
    'clients.form.fileNumber': 'رقم الملف السيادي',
    'clients.form.civilId': 'الرقم المدني',
    'clients.form.mobile': 'رقم الهاتف',
    'clients.form.assignment': 'Access Scope Assignment',
    'clients.form.engineer': 'المهندس المختص',
    'clients.form.autoAssigned': 'ربط تلقائي بالمسؤول',
    'clients.form.locationRadar': 'رادار الموقع والعنوان الذكي',
    'clients.form.mapLink': 'رابط الموقع (GOOGLE MAPS)',
    'clients.form.openMap': 'فتح الخريطة والبحث',
    'clients.form.governorate': 'المحافظة',
    'clients.form.area': 'المنطقة',
    'clients.form.block': 'القطعة',
    'clients.form.street': 'الشارع',
    'clients.form.house': 'المنزل',
    'clients.finance': 'المالية',
    'clients.newTransaction': 'فتح معاملة',

    // --- Client Dossier ---
    'clients.dossier.title': 'سجل تفاعل العملاء الشامل',
    'clients.dossier.desc': 'رؤية موحدة لرحلة العميل من التصميم المعماري إلى التسليم الميداني.',
    'clients.dossier.searchLabel': 'البحث عن عميل بالاسم أو الهاتف',
    'clients.dossier.searchPlaceholder': 'اكتب اسم العميل...',
    'clients.dossier.emptyState': 'اختر عميلاً لبدء مراجعة السجل',
    'clients.dossier.statementTitle': 'كشف سجل تفاعل العميل الشامل',
    'clients.dossier.approvedFile': 'ملف العميل المعتمد',
    'clients.dossier.table.dateTime': 'التاريخ والوقت',
    'clients.dossier.table.visitType': 'نوع الزيارة',
    'clients.dossier.table.details': 'التفاصيل والمخرجات الفنية',
    'clients.dossier.table.staff': 'المسؤول الموثق',
    'clients.dossier.visit.hall': 'اجتماع قاعة',
    'clients.dossier.visit.arch': 'زيارة معمارية',
    'clients.dossier.visit.field': 'تقرير ميداني',
    'clients.dossier.log.progress': 'توثيق إنجاز ميداني',
    'clients.dossier.tab.all': 'الكل',
    'clients.dossier.tab.field': 'الميداني',
    'clients.dossier.tab.arch': 'المعماري',
    'clients.dossier.tab.halls': 'القاعات',

    // --- Appointments Radar ---
    'appointments': 'المواعيد',
    'appointments.radar': 'رادار المواعيد والزيارات',
    'appointments.radarDesc': 'جدولة اللقاءات مع العملاء والزيارات الميدانية.',
    'appointments.printSchedule': 'طباعة الجدول',
    'appointments.hallRadar': 'رادار حجز القاعات',
    'appointments.hallRadarDesc': 'تنظيم إشغال قاعات الاجتماعات والورش الفنية.',
    'appointments.printOccupancy': 'طباعة تقرير إشغال القاعات',
    'appointments.morningSession': 'الفترة الصباحية ☀️',
    'appointments.eveningSession': 'الفترة المسائية 🌆',
    'appointments.totalToday': 'إجمالي اليوم',
    'appointments.busy': 'مشغول',
    'appointments.stats.total': 'إجمالي اليوم',
    'appointments.stats.new': 'زيارة أولى',
    'appointments.stats.follow': 'متابعة',
    'appointments.stats.contracted': 'متعاقدون',
    'appointments.action.viewRadar': 'عرض الرادار',
    'appointments.action.editBooking': 'تعديل الحجز',
    'appointments.action.delete': 'حذف وإلغاء الموعد',
    'appointments.dialog.editVisit': 'تعديل بيانات الزيارة',
    'appointments.dialog.newVisit': 'حجز موعد ميداني جديد',
    'appointments.dialog.confirmedDate': 'تاريخ الموعد المؤكد',
    'appointments.dialog.startTime': 'وقت البدء',
    'appointments.dialog.newClient': 'عميل جديد؟',
    'appointments.dialog.assignDept': 'القسم المختص بالزيارة',
    'appointments.dialog.selectSpecialty': 'تحديد التخصص المعماري...',
    'appointments.dialog.searchClient': 'بحث بالاسم أو الهاتف...',
    'appointments.dialog.linkProject': 'رابط المشروع',
    'appointments.dialog.selectProject': 'اختر المشروع المفتوح...',
    'appointments.dialog.notes': 'غرض الموعد',
    'appointments.dialog.confirm': 'تأكيد',
    'appointments.delete.title': 'حذف الموعد نهائياً',
    'appointments.delete.desc': 'هل أنت متأكد؟ سيتم إزالة هذا الموعد من كافة التقارير والرادار الزمني ولا يمكن التراجع.',
    'appointments.conflict.client': 'تعارض للعميل: يوجد موعد آخر في نفس الوقت.',
    'appointments.conflict.engineer': 'تعارض للمهندس: يوجد موعد آخر في نفس الوقت.',
    'appointments.conflict.past': 'تنبيه: لا يمكن الحجز في وقت سابق.',
    
    // --- Meeting Halls Radar ---
    'appointments.halls.schedule': 'فترة الدوام الرسمي 🏛️',
    'appointments.totalMeetings': 'إجمالي اجتماعات اليوم',
    'appointments.roomOccupancy': 'إشغال القاعات',
    'appointments.activeHalls': 'قاعات مفعلة',
    'appointments.action.viewTechRadar': 'عرض الرادار الفني',
    'appointments.action.editBooking': 'تعديل بيانات الحجز',
    'appointments.action.cancelBooking': 'حذف وإلغاء الحجز',
    'appointments.conflict.hallBusy': 'القاعة مشغولة',
    'appointments.conflict.clientConflict': 'تعارض للعميل',
    'appointments.conflict.engineerConflict': 'تعارض للمهندس',
    'appointments.professionalMeeting': 'اجتماع فني',
    'appointments.roomBooking': 'حجز قاعة اجتماع',
    'appointments.client': 'العميل المالك',
    'appointments.meetingActivity': 'نوع نشاط الاجتماع',
    'appointments.selectSpecialty': 'تحديد التخصص...',
    'appointments.noProjectsForSpecialty': 'لا يوجد معاملات لهذا التخصص',
    'appointments.department': 'القسم المسؤول',
    'appointments.leadEngineer': 'المهندس المسؤول',
    'appointments.supportingTeam': 'مهندسين مشاركين',

    // --- Projects & Contracting ---
    'projects': 'المشاريع',
    'projects.title': 'المشاريع الجارية',
    'projects.addNew': 'مشروع جديد',
    'projects.contracting': 'المقاولات',
    'projects.stats.portfolio': 'إجمالي المحفظة',
    'projects.stats.claims': 'المطالبات الجارية',
    'projects.stats.collection': 'نسبة التحصيل',
    'projects.table.project': 'المشروع',
    'projects.table.progress': 'الإنجاز',
    'projects.table.billing': 'المبالغ المفوترة',
    'projects.table.percentDone': '{pct}% إنجاز',
    'projects.table.ipcCount': '{count} مستخلصات',
    'projects.noActiveProjects': 'لا يوجد مشاريع جارية.',
    'projects.boqExplorer': 'جدول الكميات والميزانية',
    'projects.boqExplorer.desc': 'إدارة واعتماد جداول الكميات والميزانيات المرجعية',
    'projects.noBoqsRegistered': 'لا يوجد مقايسات مسجلة حالياً.',
    'projects.boqNumber': 'رقم المقايسة',
    'projects.clientName': 'العميل',
    'projects.budget': 'الميزانية',

    // --- Reports Hub ---
    'reports.hub.title': 'مركز التقارير والرقابة الهندسية',
    'reports.hub.description': 'أدوات تحليلية متقدمة لربط الميدان بالمركز المالي والإداري.',
    'reports.executive.title': 'التقرير التنفيذي الشامل',
    'reports.executive.description': 'ملخص ذكاء أعمال موحد يشمل CRM والمشاريع والمالية والـ HR في شاشة واحدة.',
    'reports.analytics.title': 'رادار الأداء المالي والإنتاجي',
    'reports.analytics.description': 'تحليل ذكي لربط ميزانيات المقايسات بالمصروفات الفعلية ونسب الإنجاز.',
    'reports.visits.title': 'سجل تفاعل العملاء والزيارات',
    'reports.visits.description': 'تحليل تاريخي لكل زيارة: الإنجاز الفني الموثق والملاحظات الميدانية.',
    'reports.stats.portfolio': 'إجمالي المحفظة',
    'reports.stats.activeProjects': 'المشاريع الجارية',
    'reports.stats.staff': 'القوى العاملة',
    'reports.stats.attendance': 'انضباط الحضور',
    'reports.charts.budgetVsExpenses': 'تحليل الميزانية vs المصروفات',
    'reports.charts.portfolioByActivity': 'توزيع المحفظة حسب النشاط',
    'reports.integrity.title': 'شهادة صحة البيانات السحابية',
    'reports.integrity.description': 'تم استخراج هذا التقرير آلياً من محرك NovaFlow ERP. كافة القيم المالية والإنتاجية تم التحقق من صحتها من خلال سجلات التدقيق المربوطة بالهوية الرقمية للمهندسين.',

    // --- General Navigation ---
    'meetings': 'الاجتماعات',
    'visitsDossier': 'سجل الزيارات',
    'reports': 'التقارير',
    'construction': 'المقاولات',
    'construction.radar': 'رادار الميدان',
    'construction.radarDesc': 'إدارة وتنسيق أطقم العمل والمهندسين في مواقع المشاريع الإنشائية.',
    'construction.printRadar': 'طباعة الرادار الميداني',
    'construction.groups': 'فرق العمل',
    'construction.groupsDesc': 'إدارة أطقم الميدان والتخصصات.',
    'construction.equipment': 'المعدات',
    'construction.reports': 'تقارير الموقع',
    'procurement': 'المشتريات',
    'suppliers': 'الموردون',
    'contracts': 'العقود',
    'aiAnalysis': 'ذكاء Nova',
    'hr': 'الموارد البشرية',
    'userProfile': 'ملفي الشخصي',
    'staffRecords': 'الموظفون',
    'leaveRequests': 'الإجازات',
    'payrollBatches': 'مسيرات الرواتب',
    'accounting': 'المحاسبة والمالية',
    'chartOfAccounts': 'شجرة الحسابات',
    'receiptVouchers': 'سندات القبض',
    'paymentVouchers': 'سندات الصرف',
    'journalEntries': 'قيود اليومية',
    'financialReports': 'التقارير المالية',
    'inventory': 'المخازن والعهد',
    'settings': 'الإعدادات',
    'usersManagement': 'المستخدمون والصلاحيات',
    'companyProfile': 'بيانات الشركة',
    'checklists': 'قواعد العمل',
    'rolesPermissions': 'الأدوار والوصول',
    'workHours': 'ساعات العمل',
    'logout': 'تسجيل الخروج',
    'devConsole': 'لوحة المطور',
    'erpSystem': 'نظام ERP الموحد',
    'erpCloud': 'سحابة Nova السيادية',

    // --- Work Groups ---
    'groups.form.name': 'اسم الطاقم',
    'groups.form.supervisor': 'المشرف المسؤول',
    'groups.form.members': 'أعضاء الطاقم',
    'groups.form.staffList': 'قائمة الموظفين',
    'groups.table.crewDept': 'الطاقم / القسم',
    'groups.table.supervisor': 'المشرف',
    'groups.table.count': 'العدد',

    // --- Status ---
    'status.active': 'نشط',
    'status.terminated': 'منتهي الخدمة',
    'status.pending': 'بانتظار المراجعة',
    'status.approved': 'معتمد',
    'status.rejected': 'مرفوض',
    'status.on-leave': 'في إجازة',
    'status.returned': 'عاد للعمل',
    'status.commenced': 'باشر العمل',
    'status.new': 'جديد',
    'status.contracted': 'متعاقد',
    'status.prospective': 'فرصة محتملة',
    'status.inactive': 'غير نشط',
    'status.draft': 'مسودة',
    'status.paid': 'تم الدفع',
    'status.active_paid': 'مفعل (مدفوع)',
    'status.scheduled': 'مجدول',
    'status.completed': 'مكتمل',
    'status.cancelled': 'ملغي',
    'status.ordered': 'تم الطلب',
    'status.reviewed': 'تمت المراجعة',

    // --- HR Core ---
    'hr.title': 'الموظفون',
    'hr.description': 'إدارة القوى العاملة والامتثال',
    'hr.addNew': 'إضافة موظف جديد',
    'hr.hire': 'تعيين',
    'hr.notFound': 'الموظف غير موجود',
    'hr.empNumLabel': 'رقم الموظف:',
    'hr.terminate': 'إنهاء الخدمة',
    'hr.confirmTermination': 'تأكيد إنهاء الخدمة',
    'hr.terminateWarning': 'تنبيه: سيتم إيقاف صرف الرواتب وتعطيل وصول الموظف للنظام فوراً.',
    'hr.terminationDate': 'تاريخ الإنهاء',
    'hr.confirmTerminationBtn': 'تأكيد الإنهاء النهائي',
    'hr.auditHistory': 'سجل التدقيق (Audit)',
    'hr.noAuditLogs': 'لا يوجد تغييرات مسجلة.',
    'hr.changedField': 'تغيير في',
    'hr.leaveRequestsTitle': 'طلبات الإجازات',
    'hr.ownRecordsOnly': 'عرض سجلاتك الشخصية فقط',
    'hr.manageAbsences': 'إدارة الغيابات والأرصدة',
    'hr.noRequests': 'لا يوجد طلبات.',
    'hr.requestNotFound': 'الطلب غير موجود',
    'hr.leaveStatus': 'حالة طلب الإجازة',
    'hr.officialAuthorization': 'إقرار إجازة رسمية',
    'hr.operationalConflict': 'تنبيه: تداخل تخصصي حرج',
    'hr.departmentOverlap': 'يوجد موظفون آخرون من نفس القسم لديهم إجازات في نفس الفترة.',
    'hr.reviewSchedule': 'يرجى مراجعة الجدول الزمني للقسم قبل اتمام الموافقه لتجنب توقف العمل.',
    'hr.adminDecision': 'قرار الإدارة وتصحيح البيانات',
    'hr.approveStart': 'تاريخ البدء المعتمد',
    'hr.approveReturn': 'تاريخ العودة المعتمد',
    'hr.deductionDays': 'أيام الخصم الفعلي (للمحاسبة)',
    'hr.internalNotes': 'ملاحظات الإدارة',
    'hr.requestDetails': 'بيانات طلب الإجازة',
    'hr.netDeduction': 'الخصم الفعلي',
    'hr.returnDate': 'تاريخ العودة',
    'hr.justification': 'المبررات والأسباب',
    'hr.auditTrail': 'سجل الحركات (Audit)',
    'hr.requestCreated': 'تقديم الطلب',
    'hr.art70Notice': 'بناءً على مادة 70: لا يحق للموظف القيام بالإجازة إلا بموافقة الإدارة. يحق للمدير تعديل تواريخ الإجازة بما يتناسب مع مصلحة العمل وضمان استمرارية القسم.',
    'hr.accessRestricted': 'وصول محجوب',
    'hr.noPayrollAccess': 'لا تملك صلاحية عرض مسيرات الرواتب.',
    'hr.payrollTitle': 'مسيرات الرواتب',
    'hr.manageFinancials': 'إدارة المستحقات المالية والخصومات التشغيلية',
    'hr.newPayrollBatch': 'توليد كشف جديد',
    'hr.createIntegratedProfile': 'إنشاء ملف تعريفي ومالي متكامل للموظف',
    'hr.submitLeaveRequest': 'تقديم طلب إجازة',
    'hr.remainingBalance': 'الرصيد المتبقي للموظف',
    'hr.applyOnBehalf': 'تقديم بالنيابة عن موظف',
    'hr.searchSelectEmployee': 'بحث واختيار الموظف',
    'hr.adminOverrideRule': 'تنبيه: كمدير، يمكنك تجاوز قيد الـ 6 أشهر عند الضرورة.',
    'hr.fieldCalculation': 'تحليل الاحتساب الميداني',
    'hr.netBalanceDeduction': 'خصم الرصيد الفعلي:',
    'hr.art70BalanceNotice': 'قانون العمل: لا تحسب الجمعة والعطلات الرسمية ضمن الإجازة السنوية (مادة 70).',
    'hr.leaveTypeRequired': 'نوع الإجازة المطلوبة',
    'hr.annualLeave': 'إجازة سنوية',
    'hr.sickLeave': 'إجازة مرضية',
    'hr.emergencyLeave': 'إجازة اضطرارية',
    'hr.unpaidLeave': 'إجازة بدون راتب',
    'hr.effectiveStartDate': 'تاريخ بداية الإجازة',
    'hr.returnToWorkDate': 'تاريخ العودة للعمل',
    'hr.leaveReasonNotes': 'سبب الإجازة / ملاحظات',
    'hr.submitForApproval': 'إرسال الطلب للاعتماد',
    'hr.payrollBatchSaved': 'تم اعتماد وحفظ كشف الرواتب.',
    'hr.smartPayrollGenerator': 'توليد الرواتب الذكي',
    'hr.integrateAttendanceData': 'نظام دمج بيانات الحضور والغياب في كشوف مالية دقيقة',
    'hr.netTotal': 'صافي المستحق',
    'hr.staffCount': 'موظف مدرج',
    'hr.reviewCalculations': 'مراجعة بيانات الرواتب قبل الاعتماد النهائي',
    'hr.basic': 'الأساسي',
    'hr.unjustified': 'غياب غير مبرر',
    'hr.net': 'الصافي',
    'hr.type': 'النوع',
    'hr.period': 'الفترة',
    'hr.workDays': 'أيام عمل',

    'details': 'التفاصيل',
    'transactions': 'المعاملات',

    // --- Legacy Keys (Preserving for sync) ---
    'inline.profile.link.failed': 'Profile Link Failed',
    'inline.account.frozen': 'Account Frozen',
    'inline.awaiting.activation': 'Awaiting Activation',
    'inline.subscription.expired': 'Subscription Expired',
    'inline.personal.workspace': 'Personal Workspace',
    'inline.tax...reg.no': 'الرقم الضريبي / السجل:',
    'inline.generated.on': 'تاريخ الاستخراج',
    '.': '.'
  },
  en: {
    // --- Common ---
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.add': 'Add',
    'common.close': 'Close',
    'common.filter': 'Filter',
    'common.confirm': 'Confirm',
    'common.search': 'Search...',
    'common.status': 'Status',
    'common.date': 'Date',
    'common.name': 'Name',
    'common.nameAr': 'Name (Arabic)',
    'common.nameEn': 'Name (EN)',
    'common.amount': 'Amount',
    'common.notes': 'Notes',
    'common.error': 'Operation Error',
    'common.saved': 'Saved Successfully',
    'common.noResults': 'No matching results',
    'common.overview': 'Overview',
    'common.reason': 'Reason',
    'common.company': 'Company',
    'common.email': 'Email',
    'common.unit': 'Unit',
    'common.quantity': 'Quantity',
    'common.total': 'Total',
    'common.days': 'Days',
    'common.print': 'Print',
    'common.editItems': 'Edit Items',
    'common.quotation': 'Quotation',
    'common.unexpectedError': 'An unexpected error occurred',
    'common.addLabel': 'Add Item',
    'common.labor': 'Labor & Workforce',
    'common.loadFromGroup': 'Load from Crew',
    'common.equipment': 'Equipment & Assets',
    'common.deleted': 'Deleted successfully',
    'common.confirmDelete': 'Confirm Delete',
    'common.retry': 'Retry',
    'common.back': 'Back',
    'common.response': 'Response',
    'common.photosUploaded': 'Photos uploaded',
    'common.saveChanges': 'Save Changes',
    'common.description': 'Description',
    'common.isActive': 'Active',
    'common.code': 'Reference Code',
    'common.alert': 'Alert',
    'common.viewAll': 'View All',
    'common.pending': 'Pending',
    'common.getStarted': 'Get Started',
    'common.records': 'Records',

    // --- Dashboard ---
    'dashboard': 'Dashboard',
    'dashboard.title': 'Operational Overview',
    'dashboard.export': 'Export Reports',
    'dashboard.missions': 'Overdue Missions',
    'dashboard.recent': 'Recent Activity',
    'dashboard.stats.revenue': 'Total Revenue',
    'dashboard.stats.activeProjects': 'Active Projects',
    'dashboard.stats.workforce': 'Workforce',
    'dashboard.stats.completion': 'Completion Rate',
    'dashboard.units.kwd': 'KWD',
    'dashboard.units.new': 'new',
    'dashboard.units.present': 'present',
    'dashboard.units.yr': 'yr',
    'dashboard.chart.revenue': 'Revenue',
    'dashboard.chart.expenses': 'Expenses',
    'dashboard.recent.quoteApproved': 'Quote Approved',
    'dashboard.recent.attendanceLogged': 'Attendance Logged',
    'dashboard.recent.paymentVoucher': 'Payment Voucher',

    // --- CRM & Clients ---
    'crm': 'CRM',
    'crm.description': 'Sales leads and commercial client management',
    'crm.newLead': 'New Lead',
    'crm.leadValue': 'Expected Value',
    'leads': 'Leads & CRM',
    'clients': 'Clients',
    'clients.title': 'Client Registry',
    'clients.registerNew': 'Register New Client',
    'clients.registerNewDesc': 'Open new commercial file for technical projects',
    'clients.editProfile': 'Edit Client Profile',
    'clients.updateSuccess': 'Client data updated successfully.',
    'clients.unauthorizedEdit': 'Unauthorized to edit clients.',
    'clients.table.profile': 'Client Profile',
    'clients.table.staff': 'Assigned Engineer',
    'clients.table.contact': 'Contact',
    'clients.details.transactions': 'Transactions & Finance',
    'clients.details.location': 'Location Radar',
    'clients.details.history': 'Interaction History',
    'clients.form.identity': 'Identity & Legal',
    'clients.form.fileNumber': 'File Number',
    'clients.form.civilId': 'Civil ID',
    'clients.form.mobile': 'Mobile Number',
    'clients.form.assignment': 'Access Scope Assignment',
    'clients.form.engineer': 'Assigned Engineer',
    'clients.form.autoAssigned': 'Auto-Assigned',
    'clients.form.locationRadar': 'Smart Location Radar',
    'clients.form.mapLink': 'Google Maps Link',
    'clients.form.openMap': 'Open Map & Search',
    'clients.form.governorate': 'Governorate',
    'clients.form.area': 'Area',
    'clients.form.block': 'Block',
    'clients.form.street': 'Street',
    'clients.form.house': 'House #',
    'clients.finance': 'Finance',
    'clients.newTransaction': 'New Trans',

    // --- Client Dossier ---
    'clients.dossier.title': 'Universal Client Dossier',
    'clients.dossier.desc': 'A unified view of the client\'s journey from architectural design to field delivery.',
    'clients.dossier.searchLabel': 'Search for a client by name or phone',
    'clients.dossier.searchPlaceholder': 'Type client name...',
    'clients.dossier.emptyState': 'Select a client to start reviewing the dossier',
    'clients.dossier.statementTitle': 'Universal Client Dossier Statement',
    'clients.dossier.approvedFile': 'Approved Client File',
    'clients.dossier.table.dateTime': 'Date & Time',
    'clients.dossier.table.visitType': 'Visit Type',
    'clients.dossier.table.details': 'Details & Technical Outputs',
    'clients.dossier.table.staff': 'Responsible Staff',
    'clients.dossier.visit.hall': 'Hall Session',
    'clients.dossier.visit.arch': 'Arch Visit',
    'clients.dossier.visit.field': 'Field Report',
    'clients.dossier.log.progress': 'Site Progress Log',
    'clients.dossier.tab.all': 'All',
    'clients.dossier.tab.field': 'Field',
    'clients.dossier.tab.arch': 'Architectural',
    'clients.dossier.tab.halls': 'Halls',

    // --- Appointments Radar ---
    'appointments': 'Appointments',
    'appointments.radar': 'Appointments Radar',
    'appointments.radarDesc': 'Schedule client meetings and site visits.',
    'appointments.printSchedule': 'Print Schedule',
    'appointments.hallRadar': 'Meeting Halls Radar',
    'appointments.hallRadarDesc': 'Organize meeting rooms and workshops.',
    'appointments.printOccupancy': 'Print Occupancy Report',
    'appointments.morningSession': 'Morning Session ☀️',
    'appointments.eveningSession': 'Evening Session 🌆',
    'appointments.totalToday': 'Total Today',
    'appointments.busy': 'Busy',
    'appointments.stats.total': 'Daily Total',
    'appointments.stats.new': 'New Visit',
    'appointments.stats.follow': 'Follow Up',
    'appointments.stats.contracted': 'Contracted',
    'appointments.action.viewRadar': 'View Radar',
    'appointments.action.editBooking': 'Edit Booking',
    'appointments.action.delete': 'Cancel Appointment',
    'appointments.dialog.editVisit': 'Edit Visit Details',
    'appointments.dialog.newVisit': 'Book New Site Visit',
    'appointments.dialog.confirmedDate': 'Confirmed Date',
    'appointments.dialog.startTime': 'Start Time',
    'appointments.dialog.newClient': 'New Client?',
    'appointments.dialog.assignDept': 'Assigned Department',
    'appointments.dialog.selectSpecialty': 'Select Arch Specialty...',
    'appointments.dialog.searchClient': 'Search Client...',
    'appointments.dialog.linkProject': 'Link to Technical Path',
    'appointments.dialog.selectProject': 'Select Active Project...',
    'appointments.dialog.notes': 'Appointment Goal',
    'appointments.dialog.confirm': 'Confirm',
    'appointments.delete.title': 'Permanent Deletion',
    'appointments.delete.desc': 'Are you sure? This appointment will be removed from all reports and radar. Cannot be undone.',
    'appointments.conflict.client': 'Client Conflict: Already has an appointment at this time.',
    'appointments.conflict.engineer': 'Engineer Conflict: Already has an appointment at this time.',
    'appointments.conflict.past': 'Alert: Cannot book in the past.',

    // --- Meeting Halls Radar ---
    'appointments.halls.schedule': 'Halls Schedule 🏛️',
    'appointments.totalMeetings': 'Daily Meetings',
    'appointments.roomOccupancy': 'Room Occupancy',
    'appointments.activeHalls': 'Active Halls',
    'appointments.action.viewTechRadar': 'View Tech Radar',
    'appointments.action.editBooking': 'Edit Booking',
    'appointments.action.cancelBooking': 'Cancel Booking',
    'appointments.conflict.hallBusy': 'Hall Busy',
    'appointments.conflict.clientConflict': 'Client Conflict',
    'appointments.conflict.engineerConflict': 'Engineer Conflict',
    'appointments.professionalMeeting': 'Professional Meeting',
    'appointments.roomBooking': 'Room Booking',
    'appointments.client': 'Client',
    'appointments.meetingActivity': 'Meeting Activity',
    'appointments.selectSpecialty': 'Select specialty...',
    'appointments.noProjectsForSpecialty': 'No projects for this specialty',
    'appointments.department': 'Department',
    'appointments.leadEngineer': 'Lead Engineer',
    'appointments.supportingTeam': 'Supporting Team',

    // --- Projects & Contracting ---
    'projects': 'Projects',
    'projects.title': 'Active Projects',
    'projects.addNew': 'New Project',
    'projects.contracting': 'Contracting',
    'projects.stats.portfolio': 'Total Portfolio',
    'projects.stats.claims': 'Active Claims',
    'projects.stats.collection': 'Collection Rate',
    'projects.table.project': 'Project',
    'projects.table.progress': 'Progress',
    'projects.table.billing': 'Billed Amount',
    'projects.table.percentDone': '{pct}% Done',
    'projects.table.ipcCount': '{count} IPCs',
    'projects.noActiveProjects': 'No active projects.',
    'projects.boqExplorer': 'BOQ Explorer',
    'projects.boqExplorer.desc': 'Manage bill of quantities and baseline budgets',
    'projects.noBoqsRegistered': 'No BOQs registered yet.',
    'projects.boqNumber': 'BOQ Number',
    'projects.clientName': 'Client',
    'projects.budget': 'Budget',

    // --- Reports Hub ---
    'reports.hub.title': 'Engineering Reports Hub',
    'reports.hub.description': 'Advanced analytics linking field logs to financial center.',
    'reports.executive.title': 'Global Executive Report',
    'reports.executive.description': 'Unified business intelligence summary covering CRM, Projects, Finance and HR.',
    'reports.analytics.title': 'Financial Performance Radar',
    'reports.analytics.description': 'Smart analysis linking BOQ budgets to actual spending and progress.',
    'reports.visits.title': 'Client Visit Dossier',
    'reports.visits.description': 'Visit-by-visit audit of technical progress and site notes.',
    'reports.stats.portfolio': 'Portfolio Value',
    'reports.stats.activeProjects': 'Active Projects',
    'reports.stats.staff': 'Total Staff',
    'reports.stats.attendance': 'Attendance',
    'reports.charts.budgetVsExpenses': 'Budget vs Expenses',
    'reports.charts.portfolioByActivity': 'Portfolio by Activity',
    'reports.integrity.title': 'Cloud Data Integrity',
    'reports.integrity.description': 'Report auto-generated by NovaFlow engine. Values verified via engineer-linked digital signatures.',

    // --- General Navigation ---
    'meetings': 'Meetings',
    'visitsDossier': 'Visits Dossier',
    'reports': 'Reports',
    'construction': 'Construction',
    'construction.radar': 'Field Radar',
    'construction.radarDesc': 'Coordinate site engineers and work crews in construction project sites.',
    'construction.printRadar': 'Print Field Radar',
    'construction.groups': 'Work Groups',
    'construction.groupsDesc': 'Field crew management.',
    'construction.equipment': 'Equipment',
    'construction.reports': 'Field Logs',
    'procurement': 'Procurement',
    'suppliers': 'Vendors',
    'contracts': 'Contracts',
    'aiAnalysis': 'Nova Intelligence',
    'hr': 'Human Resources',
    'userProfile': 'My Profile',
    'staffRecords': 'Employees',
    'leaveRequests': 'Leave Requests',
    'payrollBatches': 'Payroll Batches',
    'accounting': 'Accounting & Finance',
    'chartOfAccounts': 'Chart of Accounts',
    'receiptVouchers': 'Receipt Vouchers',
    'paymentVouchers': 'Payment Vouchers',
    'journalEntries': 'Journal Entries',
    'financialReports': 'Financial Reports',
    'inventory': 'Inventory & Assets',
    'settings': 'Settings',
    'usersManagement': 'Users & Permissions',
    'companyProfile': 'Company Data',
    'checklists': 'Operational Rules',
    'rolesPermissions': 'Access Roles',
    'workHours': 'Working Hours',
    'logout': 'Logout',
    'devConsole': 'Dev Console',
    'erpSystem': 'ERP System',
    'erpCloud': 'Nova Sovereign Cloud',

    // --- Work Groups ---
    'groups.form.name': 'Group Name',
    'groups.form.supervisor': 'Supervisor',
    'groups.form.members': 'Crew Members',
    'groups.form.staffList': 'Staff List',
    'groups.table.crewDept': 'Crew / Dept',
    'groups.table.supervisor': 'Supervisor',
    'groups.table.count': 'Count',

    // --- Status ---
    'status.active': 'Active',
    'status.terminated': 'Terminated',
    'status.pending': 'Pending Review',
    'status.approved': 'Approved',
    'status.rejected': 'Rejected',
    'status.on-leave': 'On Leave',
    'status.returned': 'Returned',
    'status.commenced': 'Commenced',
    'status.new': 'New',
    'status.contracted': 'Contracted',
    'status.prospective': 'Prospective',
    'status.inactive': 'Inactive',
    'status.draft': 'Draft',
    'status.paid': 'Paid',
    'status.active_paid': 'Active (Paid)',
    'status.scheduled': 'Scheduled',
    'status.completed': 'Completed',
    'status.cancelled': 'Cancelled',
    'status.ordered': 'Ordered',
    'status.reviewed': 'Reviewed',

    // --- HR Core ---
    'hr.title': 'Employees',
    'hr.description': 'Workforce & Compliance',
    'hr.addNew': 'Add New Employee',
    'hr.hire': 'Hire',
    'hr.notFound': 'Employee Not Found',
    'hr.empNumLabel': 'Emp #:',
    'hr.terminate': 'Terminate',
    'hr.confirmTermination': 'Confirm Termination',
    'hr.terminateWarning': 'Warning: Payroll and system access will be disabled immediately.',
    'hr.terminationDate': 'Effective Date',
    'hr.confirmTerminationBtn': 'Confirm Termination',
    'hr.auditHistory': 'Audit History',
    'hr.noAuditLogs': 'No audit logs found.',
    'hr.changedField': 'Changed',
    'hr.leaveRequestsTitle': 'Leave Requests',
    'hr.ownRecordsOnly': 'Viewing your own records only',
    'hr.manageAbsences': 'Manage absences and balances',
    'hr.noRequests': 'No requests found.',
    'hr.requestNotFound': 'Request not found',
    'hr.leaveStatus': 'Leave Request Status',
    'hr.officialAuthorization': 'Official Leave Authorization',
    'hr.operationalConflict': 'Operational Conflict Warning',
    'hr.departmentOverlap': 'Other department staff are away during this period.',
    'hr.reviewSchedule': 'Review department schedule before approval to prevent downtime.',
    'hr.adminDecision': 'Admin Decision',
    'hr.approveStart': 'Approve Start',
    'hr.approveReturn': 'Approve Return',
    'hr.deductionDays': 'Deduction Days',
    'hr.internalNotes': 'Internal Notes',
    'hr.requestDetails': 'Request Details',
    'hr.netDeduction': 'Net Deduction',
    'hr.returnDate': 'Return Date',
    'hr.justification': 'Reason / Justification',
    'hr.auditTrail': 'Audit Trail',
    'hr.requestCreated': 'Request Created',
    'hr.art70Notice': 'Art 70: Leave requires admin approval. Manager can adjust dates to suit operational needs and department continuity.',
    'hr.accessRestricted': 'Access Restricted',
    'hr.noPayrollAccess': 'You lack permissions to view payroll batches.',
    'hr.payrollTitle': 'Payroll',
    'hr.manageFinancials': 'Manage financial entitlements and operational deductions',
    'hr.newPayrollBatch': 'New Payroll Batch',
    'hr.createIntegratedProfile': 'Create integrated profile and financial record',
    'hr.submitLeaveRequest': 'Submit Leave Request',
    'hr.remainingBalance': 'Remaining Balance',
    'hr.applyOnBehalf': 'Apply on behalf of',
    'hr.searchSelectEmployee': 'Search & Select Employee',
    'hr.adminOverrideRule': 'Note: As Admin, you can override the 6-month rule if needed.',
    'hr.fieldCalculation': 'Field Calculation',
    'hr.netBalanceDeduction': 'Net Balance Deduction:',
    'hr.art70BalanceNotice': 'Art 70: Holidays/Weekends are not deducted from balance.',
    'hr.leaveTypeRequired': 'Leave Type',
    'hr.annualLeave': 'Annual Leave',
    'hr.sickLeave': 'Sick Leave',
    'hr.emergencyLeave': 'Emergency',
    'hr.unpaidLeave': 'Unpaid Leave',
    'hr.effectiveStartDate': 'Effective Start Date',
    'hr.returnToWorkDate': 'Return to Work Date',
    'hr.leaveReasonNotes': 'Reason / Notes',
    'hr.submitForApproval': 'Submit for Approval',
    'hr.payrollBatchSaved': 'Payroll batch saved.',
    'hr.smartPayrollGenerator': 'Smart Payroll Generator',
    'hr.integrateAttendanceData': 'Integrate attendance data into precise financial batch',
    'hr.netTotal': 'Net Total',
    'hr.staffCount': 'Staff Count',
    'hr.reviewCalculations': 'Review calculations before final commit',
    'hr.basic': 'Basic',
    'hr.unjustified': 'Unjustified',
    'hr.net': 'Net',
    'hr.type': 'Type',
    'hr.period': 'Period',
    'hr.workDays': 'Work Days',

    'details': 'Details',
    'transactions': 'Transactions',

    // --- Legacy Keys (Preserving for sync) ---
    'inline.profile.link.failed': 'Profile Link Failed',
    'inline.account.frozen': 'Account Frozen',
    'inline.awaiting.activation': 'Awaiting Activation',
    'inline.subscription.expired': 'Subscription Expired',
    'inline.personal.workspace': 'Personal Workspace',
    'inline.tax...reg.no': 'TAX / REG NO:',
    'inline.generated.on': 'Generated On',
    '.': '.'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>('ar');

  useEffect(() => {
    const savedLang = localStorage.getItem('lang') as Language || 'ar';
    setLang(savedLang);
  }, []);

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem('lang', newLang);
    document.documentElement.lang = newLang;
    document.documentElement.dir = newLang === 'ar' ? 'rtl' : 'ltr';
  };

  const t = (key: string) => {
    if (!key) return '';
    return translations[lang]?.[key] || key;
  };

  const tSafe = (key: string, fallbackAr: string, fallbackEn?: string) => {
    if (!key) return lang === 'ar' ? fallbackAr : (fallbackEn || fallbackAr);
    const translated = translations[lang]?.[key];
    if (translated) return translated;
    return lang === 'ar' ? fallbackAr : (fallbackEn || fallbackAr);
  };

  return (
    <LanguageContext.Provider value={{ lang, dir: lang === 'ar' ? 'rtl' : 'ltr', isRtl: lang === 'ar', setLang, t, tSafe }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
