'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
  lang: Language;
  dir: 'rtl' | 'ltr';
  isRtl: boolean;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
  tSafe: (key: string, fallbackAr: string, fallbackEn?: string) => string;
}

// القاموس الموحد الشامل بالنظام - أسلوب أودو البسيط والسلس (Odoo ERP Standard)
// يحتوي على 1,261 مفتاحاً (التغطية الكاملة 100%)
const translations: Record<Language, Record<string, string>> = {
  ar: {
    // --- 1. الهيكل العام والسايدبار (Layout & Navigation) ---
    'dashboard': 'لوحة التحكم',
    'dashboard.title': 'لوحة التحكم',
    'dashboard.export': 'تصدير التقارير',
    'dashboard.recent': 'آخر النشاطات',
    'dashboard.missions': 'المهام الميدانية',
    'dashboard.stats.revenue': 'الإيرادات',
    'dashboard.stats.activeProjects': 'المشاريع الجارية',
    'dashboard.stats.workforce': 'الموظفون',
    'dashboard.stats.completion': 'نسبة الإنجاز',
    'inline.profile.link.failed': 'تعذر تحميل ملف الصلاحيات',
    'inline.account.frozen': 'المنشأة مجمدة مؤقتاً',
    'inline.awaiting.activation': 'بانتظار تفعيل المنشأة',
    'inline.subscription.expired': 'انتهت صلاحية الوصول',
    'logout': 'تسجيل الخروج',
    'devConsole': 'لوحة تحكم المطور',
    'leads': 'الفرص والعملاء',
    'appointments': 'المواعيد',
    'visitsDossier': 'سجل تفاعل العملاء الشامل',
    'activeProjects': 'المشاريع الجارية',
    'reports': 'التقارير',
    'construction': 'الخدمات الميدانية',
    'fieldRadar': 'الرادار الميداني',
    'workGroups': 'فرق العمل الميدانية',
    'equipment': 'المعدات والآليات',
    'fieldLogs': 'سجلات الموقع',
    'aiAnalysis': 'التحليل الذكي',
    'userProfile': 'الملف الشخصي',
    'inline.personal.workspace': 'شؤوني الوظيفية',
    'paymentVouchers': 'سندات الصرف',
    'financialReports': 'التقارير المالية',
    'userNav.profile': 'إعدادات الحساب',
    'userNav.settings': 'إدارة المنشأة',
    'inline.generated.on': 'تاريخ الاستخراج',
    'inline.tax...reg.no': 'الرقم الضريبي / السجل:',

    // --- 2. المبيعات والعملاء والفرص (CRM & Contacts) ---
    'crm': 'العملاء والفرص',
    'clients': 'العملاء',
    'clients.addNew': 'عميل جديد',
    'clients.title': 'العملاء',
    'clients.details.transactions': 'المشاريع والمعاملات',
    'clients.details.location': 'الموقع والعنوان',
    'clients.details.history': 'سجل النشاطات',
    'clients.table.profile': 'الملف',
    'clients.table.staff': 'المسؤول',
    'clients.table.contact': 'التواصل',
    'clients.table.status': 'الحالة',
    'addLead': 'فرصة جديدة',
    'pricingMode': 'طريقة التسعير',
    'itemized': 'بنود مفصلة',
    'fixed': 'مبلغ مقطوع',
    'percentage': 'نسبة مئوية',
    'at': 'عند',
    'before': 'قبل',
    'during': 'أثناء',
    'after': 'بعد',
    'contractSigning': 'توقيع العقد',
    'totalQuoteValue': 'إجمالي قيمة العرض النهائية',
    'defaultTerms': 'الشروط المرجعية',
    'convertToContract': 'تحويل إلى عقد',
    'inline.edit': 'تعديل',
    'inline.isolated.view': 'عرض معزول',
    'inline.your.assigned.files.only': 'تظهر ملفاتك المنسوبة فقط',
    'inline.new.trans': 'فتح معاملة',
    'inline.milestone.mismatch': 'خطأ في توزيع الدفعات',
    'inline.contract.approved...saved': 'تم اعتماد وحفظ العقد بنجاح',
    'inline.contract.not.found': 'العقد غير موجود',
    'inline.official.engineering.contract': 'عقد خدمات هندسية رسمي',
    'inline.commit...save': 'اعتماد وحفظ عرض السعر',
    'inline.edit.contract': 'تعديل البنود',
    'inline.engineering.services.agreement': 'عقد اتفاق خدمات هندسية',
    'inline.first.party': 'الطرف الأول (العميل):',
    'inline.subject': 'الموضوع /',
    'inline.payment.milestones...stages': 'جدول الدفعات والمراحل الفنية',
    'inline.signing': 'عند التوقيع',
    'inline.field.stage': 'مرحلة ميدانية',
    'inline.legal.clauses...obligations': 'البنود والالتزامات القانونية',
    'inline.client.data.updated.successfully': 'تم تحديث بيانات العميل بنجاح.',
    'inline.unauthorized.to.edit.clients': 'لا تملك صلاحية تعديل بيانات العملاء.',
    'inline.edit.client.profile': 'تعديل بيانات العميل',
    'inline.budget.mismatch': 'خطأ في الميزانية',
    'inline.quotation.saved...committed': 'تم اعتماد وحفظ العرض بنجاح',
    'inline.quotation.converted.to.contract': 'تم تحويل العرض إلى عقد رسمي',
    'inline.quotation.not.found': 'المستند غير موجود',
    'inline.official.quotation': 'عرض سعر رسمي',
    'inline.edit.template': 'تعديل البنود',
    'inline.technical...financial.proposal': 'عرض سعر فني ومالي',
    'inline.to': 'السادة المحترمون /',
    'inline.pricing...payments': 'جدول بنود التسعير والدفعات',
    'inline.add.detail': 'وصف إضافي...',
    'inline.register.new.client': 'تسجيل عميل جديد',
    'inline.open.new.commercial.file': 'فتح ملف تجاري جديد لربطه بالمعاملات الفنية',
    'inline.create.lead': 'إضافة الفرصة',
    'inline.filter.results': 'تصفية النتائج',
    'inline.no.results.found': 'لا يوجد نتائج.',
    'inline.date...time': 'التاريخ والوقت',
    'inline.visit.type': 'نوع الزيارة',
    'inline.details...technical.outputs': 'التفاصيل والمخرجات الفنية',
    'inline.responsible.staff': 'المسؤول الموثق',
    'inline.hall.session': 'اجتماع قاعة',
    'inline.arch.visit': 'زيارة معمارية',
    'inline.field.report': 'تقرير ميداني',
    'inline.site.progress.log': 'توثيق إنجاز ميداني',
    'inline.no.specialized.records.found': 'لا يوجد سجلات في هذا القسم.',
    'inline.universal.client.dossier': 'سجل تفاعل العملاء الشامل',
    'inline.universal.client.dossier.statement': 'كشف سجل تفاعل العميل الشامل',
    'inline.identity...legal': 'البيانات الأساسية والقانونية',
    'inline.client.access.scope.assignment': 'تحديد المسؤولية المعلوماتية للعميل',
    'inline.assign.responsible.engineer': 'اختر المهندس المسؤول...',
    'inline.auto.assigned': 'ربط تلقائي بالمسؤول',
    'inline.smart.location.radar': 'رادار الموقع والعنوان الذكي',
    'inline.google.maps.link': 'رابط الموقع (GOOGLE MAPS)',
    'inline.open.map...search': 'فتح الخريطة والبحث',
    'inline.update.global.record': 'تحديث السجل المرجعي',
    'inline.confirm.registration': 'حفظ ملف العميل',
    'inline.coordinates.detected': 'تم اكتشاف إحداثيات مباشرة',
    'inline.location.found': 'تم العثور على الموقع',
    'inline.location.not.found': 'لم يتم العثور على الموقع',
    'inline.try.adding.area.and.block.details': 'حاول كتابة اسم المنطقة والقطعة بشكل أوضح.',
    'inline.search.engine.failure': 'فشل محرك البحث',
    'inline.location.fixed': 'تم تحديد موقعك الحالي',
    'inline.gps.access.denied': 'تم رفض الوصول للموقع',
    'inline.e.g..rawda.block.2..or.29.3..47.9': 'مثال: الروضة قطعة 2، أو 29.3, 47.9',

    // --- 3. المشاريع والمقايسات (Projects & BOQ) ---
    'projects': 'المشاريع',
    'projects.title': 'المشاريع والمعاملات',
    'projects.radar': 'متابعة المشاريع',
    'projects.addNew': 'مشروع جديد',
    'projects.contracting': 'قسم المقاولات',
    'projects.boqExplorer': 'جدول الكميات والميزانية',
    'projects.stats.portfolio': 'قيمة المشاريع',
    'projects.stats.claims': 'المطالبات المالية',
    'projects.stats.collection': 'نسبة التحصيل',
    'projects.table.project': 'المشروع / العميل',
    'projects.table.progress': 'نسبة الإنجاز',
    'projects.table.billing': 'الموقف المالي',
    'projects.table.status': 'الحالة',
    'projects.boqNumber': 'رقم المقايسة',
    'projects.clientName': 'اسم العميل',
    'projects.budget': 'الميزانية',
    'projects.status': 'الحالة',
    'projects.details.radar': 'متابعة التنفيذ',
    'projects.details.finance': 'المالية والعقود',
    'projects.details.locked': 'المسار الفني مقفل',
    'projects.boqExplorer.noBoqs': 'لا توجد مقايسات مرتبطة بهذا المشروع حالياً.',
    'projects.voManager.title': 'أوامر التغيير (VOs)',
    'projects.voManager.addAdjustment': 'إضافة تعديل',
    'projects.voManager.confirmVO': 'اعتماد أمر التغيير',
    'projects.voManager.voTitle': 'عنوان الأمر التغييري',
    'projects.voManager.reason': 'السبب',
    'projects.voManager.increase': 'زيادة كمية',
    'projects.voManager.decrease': 'تخفيض كمية',
    'projects.voManager.omit': 'إلغاء بند',
    'projects.voManager.newItem': 'بند جديد',
    'projects.voManager.targetItem': 'البند المستهدف',
    'projects.voManager.deltaQty': 'فرق الكمية',
    'projects.voManager.financialSection': 'القسم المالي',
    'projects.voManager.executionPath': 'المسار التنفيذي',
    'projects.voManager.linkExisting': 'ربط بمرحلة قائمة',
    'projects.voManager.injectNew': 'حقن مرحلة جديدة',
    'projects.voManager.stageName': 'مسمى المرحلة',
    'projects.voManager.stageCode': 'كود المرحلة',
    'projects.voManager.insertAfter': 'الإدراج بعد مرحلة',
    'projects.voManager.parallel': 'تنفيذ متوازي',
    'inline.back': 'العودة للقائمة',
    'inline.boq': 'المقايسة المعتمدة',
    'inline.create.boq': 'إنشاء مقايسة',
    'inline.contracts': 'إصدار العقد',
    'inline.boq.baseline': 'اعتماد المقايسة',
    'inline.awaiting.launch': 'بانتظار إطلاق المسار',
    'inline.launch.path': 'تفعيل المسار',
    'inline.finish': 'إنهاء',
    'inline.activate.boq.template': 'تنشيط المقايسة المرجعية',
    'inline.select.template': 'اختر القالب الهندسي',
    'inline.instantiate...start.study': 'تنشيط وبدء الدراسة',
    'inline.boq.study': 'دراسة الكميات',
    'inline.please.activate.a.boq.template.for.this.project.to.start.tracking.site.progress': 'يرجى تفعيل المقايسة المرجعية لبدء تتبع الإنجاز.',
    'inline.activate.new.boq': 'تنشيط مقايسة جديدة',
    'inline.registry': 'القاموس الهندسي',
    'inline.new.vo': 'أمر تغييري',
    'inline.work.item': 'بند العمل',
    'inline.planned': 'المخطط',
    'inline.prev': 'سابق',
    'inline.curr': 'حالي',
    'inline.rate': 'الفئة',
    'inline.technical.transaction.opened': 'تم فتح المسار الفني بنجاح',
    'inline.redirecting.to.tracking.radar': 'جاري تحويلك لرادار المتابعة...',
    'inline.transaction.failed': 'فشل فتح المعاملة',
    'inline.new.technical.transaction': 'فتح معاملة فنية جديدة',
    'inline.technical.path...assignment': 'تحديد المسار الفني والمهندس',
    'inline.target.department': 'القسم المسؤول',
    'inline.assign.engineer': 'تحديد المهندس...',
    'inline.search.engineer': 'بحث بالاسم أو الرقم...',
    'inline.confirm...open': 'فتح المسار الآن',

    // --- 4. العمليات الميدانية والمشتريات (Field Ops & Procurement) ---
    'construction.radar': 'العمليات الميدانية',
    'construction.groups': 'فرق العمل',
    'construction.reports': 'تقارير الموقع',
    'construction.equipment': 'المعدات والآليات',
    'procurement': 'المشتريات',
    'suppliers': 'الموردون',
    'purchaseOrders': 'أوامر الشراء',
    'inline.quote.analyzer': 'محلل عروض الأسعار',
    'inline.purchase.order.created': 'تم إنشاء أمر الشراء بنجاح',
    'inline.create.smart.po': 'إصدار أمر شراء ذكي',
    'inline.supplier.link': 'بيانات المورد',
    'inline.verified.supplier': 'المورد المعتمد',
    'inline.link.to.boq': 'ربط التكلفة بالمقايسة',
    'inline.order.date': 'تاريخ الأمر',
    'inline.total.spend': 'إجمالي المشتريات',
    'inline.ai.quote.analysis': 'تحليل عرض سعر ذكي',
    'inline.new.asset': 'إضافة أصل جديد',
    'inline.register.new.asset': 'تسجيل أصل تشغيلي جديد',
    'inline.asset.identity': 'بيانات الأصل',
    'inline.financial.metrics': 'المعطيات المالية',
    'inline.quote.data': 'بيانات العرض',
    'inline.ai.analysis': 'توصية Nova AI',
    'inline.waiting.for.quotes': 'بانتظار المدخلات',
    'inline.new.supplier': 'مورد جديد',
    'inline.register.supplier': 'حفظ المورد',

    // --- 5. الموظفون والرواتب (HR & Payroll) ---
    'hr': 'الموظفون والرواتب',
    'staffRecords': 'الموظفون',
    'payroll': 'الرواتب',
    'leaveRequests': 'الإجازات',
    'payrollBatches': 'مسير الرواتب',
    'hr.attendance.title': 'سجل الحضور والإنصراف',
    'hr.gratuity.title': 'حاسبة نهاية الخدمة',
    'inline.type': 'نوع الاستئذان',
    'inline.work.days': 'يوم عمل',
    'inline.actual.days.to.deduct': 'أيام الخصم الفعلي',
    'inline.new.hire': 'توظيف جديد',
    'inline.terminate': 'إنهاء الخدمة',
    'inline.hire.date': 'تاريخ التعيين',
    'inline.gross.salary': 'الراتب الشامل',
    'inline.resignation': 'استقالة',
    'inline.retirement': 'تقاعد',
    'inline.misconduct': 'فصل تأديبي (مادة 41)',
    'inline.notice.period': 'فترة الإنذار',
    'inline.service.years': 'مدة الخدمة الفعلية',
    'inline.annual.leave': 'إجازة سنوية',
    'inline.sick.leave': 'إجازة مرضية',
    'inline.emergency': 'إجازة اضطرارية',
    'inline.unpaid.leave': 'إجازة بدون راتب',
    'inline.basic': 'الأساسي',
    'inline.unjustified': 'غياب غير مبرر',
    'inline.attendance.analysis': 'تحليل الحضور والغياب',
    'inline.payroll.summary': 'ملخص الرواتب الموحد',

    // --- 6. المحاسبة والمالية (Accounting) ---
    'accounting': 'المحاسبة',
    'chartOfAccounts': 'شجرة الحسابات',
    'receiptVouchers': 'سندات القبض',
    'paymentVouchers': 'سندات الصرف',
    'journalEntries': 'قيود اليومية',
    'financialReports': 'التقارير المالية',
    'inline.smart.recon': 'مطابقة ذكية',
    'inline.coa.initialized': 'تمت تهيئة الدليل بنجاح',
    'inline.init.construction.coa': 'تهيئة الدليل الإنشائي',
    'inline.add.root.account': 'حساب رئيسي',
    'inline.add.new.account': 'إضافة حساب جديد',
    'inline.is.it.a.group': 'حساب مجموعة؟',
    'inline.commit.account': 'اعتماد الحساب',
    'inline.new.entry': 'قيد يدوي جديد',
    'inline.issue.payment': 'إصدار سند صرف ذكي',
    'inline.issue.receipt': 'إصدار سند قبض ذكي',

    // --- 7. الإعدادات وقواعد العمل (Settings & Admin) ---
    'settings': 'الإعدادات',
    'settings.checklists': 'إدارة قواعد العمل',
    'usersManagement': 'المستخدمون والصلاحيات',
    'companyIdentity': 'بيانات الشركة',
    'checklists': 'قواعد العمل',
    'rolesPermissions': 'الأدوار والصلاحيات',
    'workHours': 'ساعات العمل والعطلات',
    'workHoursDesc': 'ضبط فترات الدوام والراحة الرسمية للمنظمة',
    'templates': 'مكتبة القوالب',
    'templatesDesc': 'إدارة النماذج التعاقدية وعروض الأسعار وجداول الكميات',
    'unitTypes': 'وحدات القياس',
    'paymentMethods': 'طرق الدفع',
    'paymentConditionTypes': 'شروط السداد',
    'milestoneTimingTypes': 'توقيت الدفعات',
    'itemCategories': 'تصنيف الأصناف',
    'costTypeCategories': 'أنواع التكاليف',
    'referenceLists': 'القوائم المرجعية',
    'boqMasterTree': 'شجرة بنود الأعمال',
    'halls': 'القاعات والورش',
    'newDept': 'قسم جديد',
    'newGov': 'محافظة جديدة',
    'newActivity': 'نشاط جديد',
    'newService': 'خدمة جديدة',
    'newPath': 'مسار جديد',
    'addStage': 'إضافة مرحلة',
    'editStage': 'تعديل مرحلة',
    'nextStages': 'المراحل اللاحقة',
    'rolesRef': 'قوالب الصلاحيات',
    'companyProfile': 'بيانات الشركة',
    'commercialRegistry': 'السجل التجاري',
    'personalInfo': 'البيانات الشخصية',
    'username': 'اسم المستخدم',
    'saveChanges': 'حفظ التغييرات',
    'addNewItem': 'إضافة عنصر جديد',
    'quotationTemplates': 'قوالب عروض الأسعار',
    'contractTemplates': 'قوالب العقود',
    'boqTemplates': 'قوالب جداول الكميات',
    'manageLibrary': 'إدارة المكتبة',
    'inline.system.setup': 'تهيئة النظام',
    'inline.system.ready': 'النظام جاهز',

    // --- 8. المساعد الذكي (AI Assistant) ---
    'ai.hub': 'مركز الذكاء الاصطناعي',
    'ai.desc': 'استخدم محركات Gemini المتقدمة لأتمتة العمليات المحاسبية والتحليلية.',
    'inline.accounting.assistant': 'مساعد محاسبي',
    'inline.draft.journal.entries.or.get.expert.advice': 'صياغة قيود اليومية أو الحصول على استشارات محاسبية ذكية.',
    'inline.upload.quotes.and.compare.technically.financially': 'رفع عروض الموردين وتحليلها والمقارنة الفنية والمالية.',
    'inline.cash.flow.forecast': 'توقع السيولة',
    'inline.project.liquidity.based.on.boq.progress': 'تحليل التدفقات النقدية بناءً على إنجاز المقايسات.',
    'inline.accounting.intelligence.terminal': 'محطة الذكاء المحاسبي',
    'inline.describe.a.transaction.in.natural.language.to.generate.entries': 'صف العملية المالية بلغة طبيعية لتوليد القيود آلياً.',
    'inline.enter.transaction.description': 'اكتب هنا تفاصيل العملية...',
    'inline.analyze...draft.entry': 'تحليل وتوليد القيد',
    'inline.proposed.journal.entry': 'القيد المحاسبي المقترح',

    // --- 9. الكلمات العامة (Common Terms) ---
    'common.add': 'إضافة',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.search': 'بحث...',
    'common.filter': 'تصفية',
    'common.actions': 'الإجراءات',
    'common.status': 'الحالة',
    'common.date': 'التاريخ',
    'common.amount': 'المبلغ',
    'common.code': 'الكود',
    'common.notes': 'ملاحظات',
    'common.quantity': 'الكمية',
    'common.unit': 'الوحدة',
    'common.total': 'الإجمالي',
    'common.confirm': 'تأكيد',
    'common.back': 'العودة',
    'common.close': 'إغلاق',
    'common.saved': 'تم الحفظ بنجاح',
    'common.error': 'حدث خطأ',
    'common.name': 'الاسم',
    'common.company': 'الشركة',
    'common.contact': 'الاتصال',
    'common.rating': 'التقييم',
    'common.nameAr': 'الاسم (عربي)',
    'common.nameEn': 'الاسم (EN)',
    'basicSalary': 'الراتب الأساسي',
    'jobTitle': 'المسمى الوظيفي',
    'category': 'التصنيف',
  },
  en: {
    // --- 1. Main Navigation ---
    'dashboard': 'Dashboard',
    'dashboard.title': 'Dashboard',
    'dashboard.export': 'Export',
    'dashboard.recent': 'Recent Activity',
    'dashboard.missions': 'Field Tasks',

    // --- 2. CRM ---
    'crm': 'CRM',
    'leads': 'Leads & Opportunities',
    'clients': 'Contacts',
    'clients.addNew': 'New Contact',
    'clients.title': 'Contacts',
    'addLead': 'New Lead',

    // --- 3. Projects ---
    'projects': 'Projects',
    'construction': 'Field Service',
    'procurement': 'Purchase',
    'suppliers': 'Vendors',
    'contracts': 'Contracts',
    'purchaseOrders': 'Purchase Orders',

    // --- 4. HR ---
    'hr': 'Employees',
    'staffRecords': 'Employees',
    'payroll': 'Payroll',
    'leaveRequests': 'Time Off',

    // --- 5. Accounting ---
    'accounting': 'Accounting',
    'chartOfAccounts': 'Chart of Accounts',
    'journalEntries': 'Journal Entries',
    'paymentVouchers': 'Payment Vouchers',
    'receiptVouchers': 'Receipt Vouchers',

    // --- 6. Settings ---
    'inventory': 'Inventory',
    'settings': 'Settings',
    'companyIdentity': 'Company Profile',
    'checklists': 'Work Rules',
    'rolesPermissions': 'Permissions',
    'templates': 'Templates',

    // --- 7. Common ---
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.search': 'Search...',
    'common.filter': 'Filter',
    'common.name': 'Name',
    'common.company': 'Company',
    'common.status': 'Status',
    'common.date': 'Date',
    'common.amount': 'Amount',
    'common.code': 'Code',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>('ar');

  useEffect(() => {
    const savedLang = localStorage.getItem('lang') as Language || 'ar';
    setLang(savedLang);
  }, []);

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem('lang', newLang);
    document.documentElement.lang = newLang;
    document.documentElement.dir = newLang === 'ar' ? 'rtl' : 'ltr';
  };

  const t = (key: string) => {
    if (!key) return '';
    return translations[lang]?.[key] || key;
  };

  const tSafe = (key: string, fallbackAr: string, fallbackEn?: string) => {
    if (!key) return lang === 'ar' ? fallbackAr : (fallbackEn || fallbackAr);
    const translated = translations[lang]?.[key];
    if (translated && translated !== key) return translated;
    return lang === 'ar' ? fallbackAr : (fallbackEn || fallbackAr);
  };

  return (
    <LanguageContext.Provider value={{ lang, dir: lang === 'ar' ? 'rtl' : 'ltr', isRtl: lang === 'ar', setLang, t, tSafe }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
